# -*- coding: utf-8 -*-
"""초등영어 단어가 된다 4권 DAY 01~24 문장. 기준은 1~3권과 같다.

1~3권과 겹치는 단어(water·mirror·cold·want·what)는 앞 권 파일에 문장이 있으므로
여기서 다시 쓰지 않는다.
"""
DATA = {
    # ---------------- DAY 01 생각
    "discuss": "We discuss the new plan.",
    "decide": "I decide to study hard.",
    "agree": "I agree with my friend.",
    "forget": "Do not forget your key.",
    "remember": "I remember your face.",
    "think": "I think about my dream.",
    "understand": "I understand the question.",
    "solve": "I solve the math problem.",
    "problem": "This problem is very hard.",
    "question": "I have one question.",
    "guess": "Guess my age.",
    # ---------------- DAY 02 마음
    "believe": "I believe your story.",
    "hope": "I hope for good weather.",
    "lie": "Do not tell a lie.",
    "hate": "I hate cold weather.",
    "invite": "I invite my friends.",
    "hurry": "Hurry or we are late.",
    "arrive": "We arrive at nine.",
    "invent": "I want to invent a robot.",
    "fix": "My father can fix the bike.",
    "rest": "I need a short rest.",
    # ---------------- DAY 03 시작과 끝
    "start": "We start at seven.",
    "finish": "I finish my homework.",
    "begin": "The class will begin soon.",
    "end": "The movie will end late.",
    "need": "I need a new pencil.",
    "help": "I help my mother.",
    "bring": "Bring your book tomorrow.",
    "borrow": "May I borrow your pen?",
    "find": "I find my lost cap.",
    "use": "May I use your phone?",
    # ---------------- DAY 04 의문사
    "who": "Who is that man?",
    "when": "When do you go home?",
    "where": "Where is my bag?",
    "how": "How do you go to school?",
    "why": "Why are you so happy?",
    "how many": "How many books do you have?",
    "how much": "How much water do you drink?",
    "how old": "How old is your sister?",
    # ---------------- DAY 05 하루 일과
    "get up": "I get up at seven.",
    "go to bed": "I go to bed at ten.",
    "have breakfast": "I have breakfast with my mom.",
    "have lunch": "I have lunch with my friends.",
    "have dinner": "We have dinner together.",
    "go to school": "I go to school by bus.",
    "come home": "I come home at five.",
    "do my homework": "I do my homework after dinner.",
    "ride a bike": "I ride a bike every day.",
    "wash the dishes": "I wash the dishes at night.",
    "brush my teeth": "I brush my teeth every morning.",
    # ---------------- DAY 06 달
    "January": "January is very cold.",
    "February": "February is a short month.",
    "March": "School starts in March.",
    "April": "Flowers open in April.",
    "May": "May is a warm month.",
    "June": "June is the sixth month.",
    "July": "July is very hot.",
    "August": "We go to the sea in August.",
    "September": "September is cool and nice.",
    "October": "Leaves turn red in October.",
    "November": "November is the eleventh month.",
    "December": "Christmas is in December.",
    # ---------------- DAY 07 서수
    "first": "I am first in line.",
    "third": "This is my third book.",
    "fourth": "This is the fourth day.",
    "fifth": "I sit in the fifth seat.",
    "sixth": "The sixth day is Saturday.",
    "seventh": "My room is on the seventh floor.",
    "eighth": "This is my eighth book.",
    "ninth": "The ninth question is hard.",
    "tenth": "Today is the tenth day.",
    "eleventh": "The eleventh box is empty.",
    "twelfth": "December is the twelfth month.",
    # ---------------- DAY 08 시간
    "time": "What time is it now?",
    "calendar": "I look at the calendar.",
    "second": "Please wait one second.",
    "minute": "I wait ten minutes.",
    "hour": "I read for one hour.",
    "past": "Do not think about the past.",
    "now": "I am busy now.",
    "future": "I dream about my future.",
    "a.m.": "I get up at seven a.m.",
    "p.m.": "I go home at four p.m.",
    # ---------------- DAY 09 취미
    "enjoy": "I enjoy my free time.",
    "favorite": "Blue is my favorite color.",
    "interesting": "This book is very interesting.",
    "boring": "The show was very boring.",
    "free time": "I read in my free time.",
    "hobby": "My hobby is reading books.",
    "comic book": "I read a comic book.",
    "game": "We play a fun game.",
    "show": "The show starts at seven.",
    "movie": "We watch a movie together.",
    "musical": "The musical was very great.",
    "theater": "We go to the theater.",
    # ---------------- DAY 10 이야기
    "king": "The king lives in a castle.",
    "queen": "The queen is very kind.",
    "prince": "The prince is very brave.",
    "princess": "The princess has long hair.",
    "knight": "The knight rides a horse.",
    "castle": "The castle is very old.",
    "angel": "An angel has white wings.",
    "ghost": "I am not afraid of a ghost.",
    "fairy tale": "I like this fairy tale.",
    "story": "Tell me a funny story.",
    # ---------------- DAY 11 나들이
    "go shopping": "We go shopping on Sunday.",
    "go camping": "We go camping in summer.",
    "go fishing": "I go fishing with my dad.",
    "go skating": "We go skating in winter.",
    "go skiing": "I go skiing every winter.",
    "go running": "I go running every morning.",
    "go hiking": "We go hiking in the fall.",
    "go swimming": "I go swimming in the pool.",
    "go surfing": "They go surfing at the beach.",
    # ---------------- DAY 12 행사
    "Christmas": "I love Christmas.",
    "letter": "I write a letter to my friend.",
    "present": "I open my birthday present.",
    "marry": "My aunt will marry in May.",
    "wedding": "The wedding was very beautiful.",
    "festival": "We go to a music festival.",
    "holiday": "Today is a holiday.",
    "prize": "I win first prize.",
    "luck": "Good luck on your test.",
    # ---------------- DAY 13 몸
    "skin": "My skin is very dry.",
    "bone": "The dog eats a bone.",
    "blood": "Blood is red.",
    "brain": "The brain needs rest.",
    "heart": "My heart beats fast.",
    "forehead": "My forehead is hot.",
    "eyebrow": "My eyebrow is very thin.",
    "cheek": "Her cheek is pink.",
    "voice": "She has a nice voice.",
    "height": "My height is very tall.",
    "weight": "My weight is not heavy.",
    # ---------------- DAY 14 소지품
    "belt": "My belt is black.",
    "scarf": "I wear a warm scarf.",
    "sweater": "This sweater is very soft.",
    "jeans": "My jeans are too long.",
    "button": "The button is very small.",
    "pocket": "My key is in my pocket.",
    "sneakers": "My sneakers are white.",
    "sunglasses": "I wear sunglasses in summer.",
    "wallet": "My wallet is empty.",
    "key": "I lost my house key.",
    "cell phone": "My cell phone is new.",
    # ---------------- DAY 15 욕실
    "soap": "I wash my hands with soap.",
    "shampoo": "I need new shampoo.",
    "toothbrush": "My toothbrush is blue.",
    "toothpaste": "The toothpaste is almost empty.",
    "towel": "The towel is very soft.",
    "take a shower": "I take a shower every night.",
    "closet": "My closet is very full.",
    "pillow": "My pillow is very soft.",
    "blanket": "This blanket is very warm.",
    # ---------------- DAY 16 아플 때
    "sick": "I am sick today.",
    "fever": "I have a high fever.",
    "runny nose": "I have a runny nose.",
    "stomachache": "I have a bad stomachache.",
    "toothache": "I have a toothache.",
    "headache": "I have a headache now.",
    "hurt": "My leg hurts a lot.",
    "medicine": "I take medicine after lunch.",
    "health": "Sleep is good for health.",
    "healthy": "I eat healthy food.",
    "virus": "A virus makes us sick.",
    # ---------------- DAY 17 동물원
    "wolf": "The wolf lives in the forest.",
    "fox": "The fox is very clever.",
    "kangaroo": "A kangaroo jumps very high.",
    "eagle": "The eagle flies very high.",
    "iguana": "An iguana is a green animal.",
    "alligator": "The alligator has big teeth.",
    "penguin": "A penguin cannot fly.",
    "swan": "The swan is very white.",
    "parrot": "My parrot can talk.",
    "cage": "The bird is in the cage.",
    "fence": "The fence is very high.",
    "tail": "The cat has a long tail.",
    # ---------------- DAY 18 환경
    "air": "The air is very clean.",
    "fire": "The fire is very hot.",
    "energy": "We must save energy.",
    "gold": "My ring is gold.",
    "silver": "The spoon is silver.",
    "save": "We save water every day.",
    "recycle": "We recycle paper and cans.",
    "bottle": "I drink from a bottle.",
    "can": "I can swim very well.",
    "glass": "The glass is very clean.",
    "plastic": "This box is plastic.",
    # ---------------- DAY 19 성질 1
    "nice": "You have a nice smile.",
    "fun": "The party was very fun.",
    "high": "The wall is very high.",
    "dark": "The room is too dark.",
    "soft": "The bed is very soft.",
    "hard": "This bread is very hard.",
    "clean": "My hands are clean.",
    "dirty": "My shoes are very dirty.",
    "easy": "This question is easy.",
    "difficult": "The test was difficult.",
    "same": "We are in the same class.",
    "different": "We have different ideas.",
    # ---------------- DAY 20 성질 2
    "strong": "My brother is very strong.",
    "weak": "The old cat is weak.",
    "full": "My bag is full.",
    "empty": "The box is empty.",
    "wet": "My socks are wet.",
    "dry": "The towel is dry.",
    "clever": "My sister is very clever.",
    "fat": "The pig is very fat.",
    "important": "Sleep is very important.",
    "quick": "He gives a quick answer.",
    "dead": "The old tree is dead.",
    "clear": "The water is very clear.",
    # ---------------- DAY 21 길과 안전
    "street": "The street is very busy.",
    "road": "The road is very long.",
    "highway": "The highway is very wide.",
    "traffic jam": "We are in a traffic jam.",
    "crosswalk": "Cross at the crosswalk.",
    "traffic light": "Stop at the traffic light.",
    "drive": "My father will drive us home.",
    "speed": "The car has high speed.",
    "seat belt": "Wear your seat belt.",
    "helmet": "I wear a helmet on my bike.",
    "safe": "This place is very safe.",
    "dangerous": "The road is dangerous at night.",
    # ---------------- DAY 22 빈도
    "never": "I never drink soda.",
    "sometimes": "I sometimes walk to school.",
    "often": "We often play together.",
    "usually": "I usually get up early.",
    "always": "She is always kind to me.",
    "once": "I meet him once a week.",
    "twice": "I brush my teeth twice a day.",
    "every": "I read every night.",
    "only": "I have only one pencil.",
    # ---------------- DAY 23 기분
    "afraid": "I am afraid of dogs.",
    "calm": "The sea is very calm.",
    "fine": "I feel fine today.",
    "glad": "I am glad to meet you.",
    "curious": "I am curious about space.",
    "fantastic": "The show was fantastic.",
    "lonely": "I feel lonely at night.",
    "upset": "She is upset about the news.",
    "great": "You did a great job.",
    "famous": "He is a famous singer.",
    "rich": "The rich man helps people.",
    "poor": "The poor dog is very thin.",
    # ---------------- DAY 24 모양과 크기
    "dot": "Draw a small dot here.",
    "line": "Draw a long line.",
    "size": "What size are your shoes?",
    "circle": "Draw a big circle.",
    "triangle": "This is a small triangle.",
    "square": "Draw a square on the paper.",
    "large": "They live in a large house.",
    "heavy": "This box is very heavy.",
    "light": "My bag is very light.",
    "long": "My hair is very long.",
    "short": "My pencil is too short.",
}
