# -*- coding: utf-8 -*-
"""초등영어 단어가 된다 1권 DAY 01~24 문장.

초1~3용. 3~6단어, 현재형. `I have / I like / I love / I know / I go / I eat` 계열과
`My ~ is ~` 계열을 섞는다. 표제어는 원형 그대로 들어간다.
"""
DATA = {
    # ---------------- DAY 01 인사
    "hello": "I say hello to you.",
    "hi": "I say hi to my friend.",
    "goodbye": "I say goodbye to my teacher.",
    "bye": "I wave and say bye.",
    "my": "This is my book.",
    "your": "Is this your bag?",
    "what": "What is your name?",
    "name": "I write my name.",
    # ---------------- DAY 02 대명사
    "I": "I am a student.",
    "you": "You are my friend.",
    "we": "We go to school.",
    "she": "She is my sister.",
    "he": "He is my brother.",
    "they": "They are my friends.",
    "this": "This is a red apple.",
    "that": "That is a big tree.",
    # ---------------- DAY 03 얼굴·몸
    "eye": "I have two eyes.",
    "nose": "My nose is small.",
    "mouth": "I open my mouth.",
    "ear": "I have two ears.",
    "face": "My face is warm.",
    "hand": "I wash my hands.",
    "foot": "My foot is cold.",
    "body": "My body is strong.",
    # ---------------- DAY 04 가족
    "family": "I love my family.",
    "grandma": "My grandma is very kind.",
    "grandpa": "My grandpa is old.",
    "mom": "My mom likes flowers.",
    "dad": "My dad is tall.",
    "love": "I love my mom.",
    "sister": "My sister is small.",
    "brother": "My brother is fast.",
    # ---------------- DAY 05 방
    "room": "My room is big.",
    "bed": "My bed is soft.",
    "clock": "The clock is on the wall.",
    "puzzle": "I like this puzzle.",
    "door": "I open the door.",
    "window": "The window is open.",
    "robot": "I have a small robot.",
    "doll": "My doll is very pretty.",
    "toy": "I love my new toy.",
    # ---------------- DAY 06 학용품
    "bag": "My bag is heavy.",
    "book": "I read a good book.",
    "notebook": "My notebook is new.",
    "pencil": "I have a long pencil.",
    "eraser": "My eraser is small.",
    "pencil case": "My pencil case is blue.",
    "scissors": "I cut paper with scissors.",
    "glue": "I need some glue.",
    "ruler": "My ruler is long.",
    # ---------------- DAY 07 학교
    "school": "I go to school.",
    "classroom": "My classroom is clean.",
    "bell": "The bell rings at nine.",
    "teacher": "My teacher is very kind.",
    "student": "I am a good student.",
    "friend": "He is my best friend.",
    "desk": "My desk is small.",
    "chair": "This chair is very old.",
    # ---------------- DAY 08 기분
    "happy": "I am happy today.",
    "sad": "She is sad now.",
    "angry": "My dad is angry.",
    "sorry": "I am sorry, mom.",
    "tired": "I am very tired.",
    "sleepy": "I am sleepy at night.",
    "hungry": "I am hungry now.",
    "thirsty": "I am thirsty, mom.",
    # ---------------- DAY 09 동물
    "animal": "I like every animal.",
    "dog": "My dog runs to me.",
    "puppy": "The puppy is very small.",
    "cat": "My cat is white.",
    "kitten": "The kitten is so small.",
    "bird": "A bird sings for me.",
    "rabbit": "The rabbit eats a carrot.",
    "mouse": "A mouse is very small.",
    # ---------------- DAY 10 농장
    "farm": "My grandpa has a farm.",
    "farmer": "The farmer works all day.",
    "cow": "The cow eats grass.",
    "horse": "The horse runs fast.",
    "sheep": "The sheep is white.",
    "pig": "The pig is very big.",
    "chicken": "The chicken has two legs.",
    "duck": "A duck swims in water.",
    # ---------------- DAY 11 곤충·작은 동물
    "ant": "An ant is very small.",
    "bee": "A bee likes flowers.",
    "butterfly": "The butterfly is yellow.",
    "spider": "I see a black spider.",
    "frog": "The frog jumps high.",
    "ladybug": "A ladybug is red.",
    "fish": "I have three fish.",
    "snake": "The snake is very long.",
    # ---------------- DAY 12 동물원
    "zoo": "I go to the zoo.",
    "lion": "The lion is very strong.",
    "tiger": "The tiger has big teeth.",
    "elephant": "An elephant has a long nose.",
    "panda": "The panda eats and sleeps.",
    "zebra": "A zebra is black and white.",
    "giraffe": "The giraffe is very tall.",
    "monkey": "A monkey eats a banana.",
    "bear": "The bear is very big.",
    # ---------------- DAY 13 과일
    "apple": "I eat a red apple.",
    "banana": "The banana is yellow.",
    "grape": "I like this green grape.",
    "strawberry": "A strawberry is small and red.",
    "watermelon": "The watermelon is very big.",
    "orange": "I eat an orange every day.",
    "like": "I like my new bike.",
    "pear": "This pear is very sweet.",
    "lemon": "A lemon is yellow.",
    "kiwi": "I eat a green kiwi.",
    "fruit": "I love sweet fruit.",
    # ---------------- DAY 14 채소
    "egg": "I eat an egg.",
    "cheese": "My cat likes cheese.",
    "tomato": "The tomato is very red.",
    "potato": "I eat a hot potato.",
    "corn": "The corn is yellow.",
    "pumpkin": "The pumpkin is very big.",
    "carrot": "My rabbit eats a carrot.",
    "onion": "The onion is white.",
    "vegetable": "I eat every vegetable.",
    # ---------------- DAY 15 음식
    "food": "I love good food.",
    "rice": "I eat rice every day.",
    "bread": "The bread is warm.",
    "pizza": "I like hot pizza.",
    "hamburger": "I eat a big hamburger.",
    "salad": "My mom makes a salad.",
    "soup": "I eat warm soup.",
    "curry": "I like hot curry.",
    # ---------------- DAY 16 후식·음료
    "dessert": "I want a sweet dessert.",
    "ice cream": "I eat cold ice cream.",
    "chocolate": "I love sweet chocolate.",
    "candy": "This candy is very sweet.",
    "cookie": "I eat one cookie.",
    "cake": "My cake is very big.",
    "water": "I drink cold water.",
    "milk": "I drink warm milk.",
    "juice": "I like apple juice.",
    # ---------------- DAY 17 숫자
    "one": "I have one brother.",
    "two": "I see two birds.",
    "three": "I have three books.",
    "four": "My cat has four legs.",
    "five": "I have five fingers.",
    "six": "I see six flowers.",
    "seven": "I have seven pencils.",
    "eight": "A spider has eight legs.",
    "nine": "I go to bed at nine.",
    "ten": "I have ten toes.",
    "number": "My number is seven.",
    # ---------------- DAY 18 반대말
    "good": "This is a good book.",
    "bad": "That is a bad dog.",
    "big": "My dog is big.",
    "small": "My cat is small.",
    "fast": "My brother is very fast.",
    "slow": "The old cow is slow.",
    "new": "I have a new bag.",
    "old": "My bike is very old.",
    "it": "It is a red ball.",
    # ---------------- DAY 19 색깔
    "red": "My hat is red.",
    "yellow": "The sun is yellow.",
    "green": "The tree is green.",
    "blue": "The sky is blue.",
    "purple": "My bag is purple.",
    "pink": "Her doll is pink.",
    "brown": "My dog is brown.",
    "black": "My cat is black.",
    "white": "The snow is white.",
    "color": "My color is blue.",
    # ---------------- DAY 20 하루
    "early": "I go to bed early.",
    "late": "I am late for school.",
    "day": "Today is a good day.",
    "night": "I sleep at night.",
    "morning": "I run in the morning.",
    "noon": "I eat lunch at noon.",
    "afternoon": "I play in the afternoon.",
    "evening": "We eat dinner in the evening.",
    # ---------------- DAY 21 동작
    "walk": "I walk to school.",
    "run": "I run very fast.",
    "jump": "I jump very high.",
    "go": "I go to the park.",
    "stand": "I stand by the door.",
    "sit": "I sit on my chair.",
    "sing": "I sing a happy song.",
    "dance": "We dance and sing.",
    "swim": "I swim in the pool.",
    # ---------------- DAY 22 공원
    "park": "I play in the park.",
    "ball": "I have a red ball.",
    "bat": "I hold a long bat.",
    "tree": "The tree is very tall.",
    "flower": "This flower is pink.",
    "picnic": "We go on a picnic.",
    "bench": "I sit on the bench.",
    "skateboard": "My skateboard is fast.",
    "bike": "I ride my new bike.",
    # ---------------- DAY 23 날씨
    "rain": "I like the rain.",
    "snow": "The snow is very white.",
    "wind": "The wind is cold.",
    "rainbow": "I see a big rainbow.",
    "snowman": "We make a big snowman.",
    "cloud": "The cloud is white.",
    "umbrella": "My umbrella is blue.",
    "boots": "My boots are yellow.",
    "gloves": "My gloves are warm.",
    # ---------------- DAY 24 날씨 표현
    "warm": "My room is warm.",
    "hot": "The soup is very hot.",
    "cool": "The wind is cool.",
    "cold": "My hands are cold.",
    "sunny": "Today is sunny and warm.",
    "cloudy": "It is cloudy today.",
    "windy": "It is windy and cold.",
    "rainy": "I like a rainy day.",
    "snowy": "It is snowy today.",
    "weather": "The weather is very good.",
}
