# -*- coding: utf-8 -*-
"""초등영어 단어가 된다 3권 DAY 01~24 문장. 기준은 1·2권과 같다."""
DATA = {
    # ---------------- DAY 01 자연
    "nature": "I love nature.",
    "hill": "I run up the hill.",
    "cave": "The cave is very dark.",
    "lake": "The lake is very quiet.",
    "forest": "Many animals live in the forest.",
    "field": "The field is very green.",
    "stone": "I find a small stone.",
    "rock": "The rock is very big.",
    "wood": "This chair is made of wood.",
    "sand": "I play in the sand.",
    # ---------------- DAY 02 우주
    "space": "I want to go to space.",
    "star": "I see many stars.",
    "Sun": "The Sun is very hot.",
    "Earth": "We live on Earth.",
    "Moon": "The Moon is bright tonight.",
    "land": "We see land from the boat.",
    "ocean": "The ocean is very deep.",
    "sky": "The sky is blue today.",
    "mountain": "The mountain is very high.",
    "river": "The river is very long.",
    # ---------------- DAY 03 계절
    "season": "Spring is my favorite season.",
    "spring": "I like warm spring.",
    "summer": "Summer is very hot.",
    "fall": "I like cool fall.",
    "winter": "Winter is very cold.",
    "leaf": "A leaf falls from the tree.",
    "branch": "A bird sits on the branch.",
    "grass": "The grass is very green.",
    "plant": "I water the plant.",
    # ---------------- DAY 04 바다
    "yacht": "The yacht is very big.",
    "dolphin": "A dolphin swims very fast.",
    "island": "We go to a small island.",
    "tent": "We sleep in a tent.",
    "beach": "I play on the beach.",
    "wave": "The wave is very high.",
    "sea": "The sea is very blue.",
    "sandcastle": "I make a sandcastle.",
    "turtle": "The turtle is very slow.",
    "boat": "We ride a small boat.",
    # ---------------- DAY 05 과목
    "subject": "Math is my favorite subject.",
    "textbook": "I open my textbook.",
    "Korean": "I speak Korean and English.",
    "English": "I study English every day.",
    "social studies": "I like social studies.",
    "history": "I like history class.",
    "math": "Math is not easy.",
    "science": "I love science class.",
    "art": "I draw in art class.",
    "music": "We sing in music class.",
    # ---------------- DAY 06 학교 생활
    "grade": "I am in third grade.",
    "class": "My class has twenty students.",
    "vacation": "I love summer vacation.",
    "homework": "I do my homework.",
    "quiz": "We have a math quiz.",
    "test": "The test was very easy.",
    "score": "My score is very good.",
    "practice": "I practice the piano.",
    "exercise": "I exercise every morning.",
    # ---------------- DAY 07 학교
    "elementary school": "I go to elementary school.",
    "middle school": "My sister goes to middle school.",
    "high school": "My brother goes to high school.",
    "college": "My uncle teaches at college.",
    "university": "She studies at a university.",
    "school uniform": "I wear a school uniform.",
    "gym": "We play in the gym.",
    "pool": "Our school has a big pool.",
    "locker": "My locker is very small.",
    # ---------------- DAY 08 운동
    "team": "Our team is very strong.",
    "player": "He is a good player.",
    "coach": "Our coach is very kind.",
    "cheer": "We cheer for our team.",
    "throw": "I throw the ball.",
    "kick": "I kick the ball hard.",
    "pass": "I pass the ball to you.",
    "hit": "I hit the ball.",
    "catch": "I catch the ball.",
    "jump rope": "I jump rope every day.",
    # ---------------- DAY 09 장래
    "plan": "I have a good plan.",
    "chance": "This is my last chance.",
    "dream": "My dream is very big.",
    "job": "My father has a new job.",
    "work": "My parents work very hard.",
    "become": "I want to become a teacher.",
    "doctor": "The doctor helps sick people.",
    "nurse": "The nurse is very kind.",
    "firefighter": "A firefighter is very brave.",
    "police officer": "The police officer helps us.",
    # ---------------- DAY 10 직업 1
    "singer": "She is a great singer.",
    "dancer": "My sister is a good dancer.",
    "actor": "He is a movie actor.",
    "artist": "The artist draws every day.",
    "musician": "My uncle is a musician.",
    "pianist": "She is a young pianist.",
    "designer": "My aunt is a designer.",
    "model": "The model is very tall.",
    "astronaut": "An astronaut goes to space.",
    "cook": "My mother is a good cook.",
    "baker": "The baker makes fresh bread.",
    "soccer player": "He is a soccer player.",
    # ---------------- DAY 11 직업 2
    "vet": "The vet helps my dog.",
    "dentist": "I visit the dentist today.",
    "soldier": "The soldier is very brave.",
    "pilot": "The pilot flies the airplane.",
    "flight attendant": "The flight attendant is kind.",
    "photographer": "The photographer takes pictures.",
    "scientist": "My dream is to be a scientist.",
    "engineer": "My father is an engineer.",
    "lawyer": "The lawyer helps many people.",
    # ---------------- DAY 12 동작
    "call": "I call my grandma.",
    "speak": "I speak English well.",
    "wait": "I wait for the bus.",
    "meet": "I meet my friend today.",
    "search": "I search for my key.",
    "give": "I give a gift to mom.",
    "collect": "I collect old coins.",
    "send": "I send a letter.",
    "join": "I want to join the team.",
    "choose": "I choose the red one.",
    "teach": "My mother teaches math.",
    # ---------------- DAY 13 나라
    "Korea": "I live in Korea.",
    "the U.S.": "My uncle lives in the U.S.",
    "China": "China is a big country.",
    "France": "France is far from Korea.",
    "India": "India has many people.",
    "Canada": "Canada is very cold.",
    "nation": "Korea is a small nation.",
    "north": "The wind comes from the north.",
    "west": "My house is west of here.",
    "east": "The east side is bright.",
    "south": "Busan is in the south.",
    # ---------------- DAY 14 세계
    "American": "He is an American singer.",
    "Chinese": "I like Chinese food.",
    "French": "French bread is delicious.",
    "Indian": "Indian curry is very good.",
    "Canadian": "My friend is Canadian.",
    "world": "The world is very big.",
    "culture": "I like Korean culture.",
    "language": "English is a world language.",
    "flag": "Our flag is very beautiful.",
    # ---------------- DAY 15 여행
    "trip": "We go on a school trip.",
    "tour": "We join a city tour.",
    "travel": "I want to travel the world.",
    "go on a trip": "We go on a trip in summer.",
    "tourist": "The tourist takes many pictures.",
    "passport": "I need my passport.",
    "map": "I look at the map.",
    "visit": "I visit my grandma.",
    "hotel": "We stay at a hotel.",
    "stay": "I stay at home today.",
    # ---------------- DAY 16 도시
    "building": "The building is very tall.",
    "tower": "The tower is very high.",
    "bridge": "We cross the bridge.",
    "palace": "The palace is very old.",
    "design": "I design a new car.",
    "build": "They build a new school.",
    "town": "My town is very small.",
    "city": "Seoul is a big city.",
    "country": "Korea is my country.",
    # ---------------- DAY 17 장소
    "place": "This is a quiet place.",
    "library": "I read books in the library.",
    "post office": "I go to the post office.",
    "museum": "We visit the museum.",
    "police station": "The police station is near.",
    "fire station": "Firefighters work at the fire station.",
    "bank": "My mother works at a bank.",
    "city hall": "We meet at the city hall.",
    "hospital": "The hospital is near my house.",
    "stadium": "The stadium is very big.",
    # ---------------- DAY 18 길 찾기
    "straight": "Draw a straight line.",
    "left": "My left hand is strong.",
    "right": "Use your right hand.",
    "turn left": "Turn left at the corner.",
    "go straight": "Go straight for two blocks.",
    "turn right": "Turn right at the bank.",
    "corner": "The shop is on the corner.",
    "block": "Walk one block and stop.",
    "cross": "Cross the street here.",
    "top": "The bird is on the top.",
    "middle": "I sit in the middle.",
    "bottom": "My book is on the bottom.",
    # ---------------- DAY 19 위치
    "here": "Come here, please.",
    "there": "My bag is over there.",
    "near": "The school is very near.",
    "close to": "My house is close to school.",
    "far from": "The park is far from here.",
    "across from": "The bank is across from us.",
    "around": "We walk around the lake.",
    "above": "The clock is above the door.",
    "below": "The cat is below the table.",
    "beside": "I sit beside my friend.",
    # ---------------- DAY 20 탈것
    "car": "My father has a new car.",
    "bus": "I take the bus to school.",
    "subway": "The subway is very fast.",
    "train": "The train is very long.",
    "ship": "The ship is very big.",
    "airplane": "The airplane flies very high.",
    "taxi": "We take a taxi home.",
    "truck": "A big truck stops here.",
    "helicopter": "The helicopter is very loud.",
    "take": "Please take my hand.",
    "get on": "I get on the bus.",
    "get off": "I get off at the next stop.",
    # ---------------- DAY 21 가게
    "market": "We buy fruit at the market.",
    "store": "The store is very big.",
    "shop": "I shop with my mother.",
    "customer": "The customer is very kind.",
    "clerk": "The clerk helps me.",
    "bakery": "The bakery smells very good.",
    "bookstore": "I buy books at the bookstore.",
    "flower shop": "The flower shop is very pretty.",
    "department store": "We go to the department store.",
    "restaurant": "We eat at a new restaurant.",
    # ---------------- DAY 22 사고팔기
    "sell": "They sell fresh fruit.",
    "buy": "I buy a new pencil.",
    "pay": "I pay ten dollars.",
    "cost": "The book costs five dollars.",
    "expensive": "This bag is very expensive.",
    "cheap": "These shoes are very cheap.",
    "sale": "The store has a big sale.",
    "money": "I save my money.",
    "credit card": "My father has a credit card.",
    "cash": "I pay in cash.",
    "coin": "I have three coins.",
    # ---------------- DAY 23 외식
    "eat out": "We eat out on Sunday.",
    "menu": "I look at the menu.",
    "order": "I order a pizza.",
    "lemonade": "I drink cold lemonade.",
    "chopsticks": "I eat with chopsticks.",
    "noodle": "I like hot noodles.",
    "dish": "This dish is very good.",
    "pancake": "I eat a sweet pancake.",
    "spaghetti": "Spaghetti is my favorite food.",
    "steak": "My father likes steak.",
    # ---------------- DAY 24 맛
    "yummy": "The cake is very yummy.",
    "delicious": "This pizza is delicious.",
    "fresh": "I like fresh fruit.",
    "sweet": "The candy is very sweet.",
    "salty": "The soup is too salty.",
    "sour": "The lemon is very sour.",
    "bitter": "This tea is very bitter.",
    "spicy": "Korean food is very spicy.",
}
