# -*- coding: utf-8 -*-
"""초등영어 단어가 된다 2권 DAY 01~24 문장.

기준은 1권과 같다(3~6단어, 현재형, `I have`·`My ~ is ~` 계열을 섞음).
1권과 겹치는 단어(cake·day·old)는 1권 파일에 문장이 있으므로 여기서 다시 쓰지 않는다.
"""
DATA = {
    # ---------------- DAY 01 몸
    "head": "I have one head.",
    "hair": "I love my hair.",
    "neck": "My neck is long.",
    "tooth": "I have a small tooth.",
    "shoulder": "My shoulders are strong.",
    "arm": "I have two arms.",
    "finger": "I have ten fingers.",
    "leg": "My legs are long.",
    "knee": "I have two knees.",
    "toe": "My toes are very small.",
    # ---------------- DAY 02 가족
    "parents": "I love my parents.",
    "son": "He is my son.",
    "daughter": "She is my daughter.",
    "father": "My father is very tall.",
    "mother": "My mother is kind.",
    "husband": "Her husband is a teacher.",
    "wife": "His wife is a doctor.",
    "uncle": "My uncle has a car.",
    "aunt": "My aunt makes good food.",
    "cousin": "My cousin is my friend.",
    # ---------------- DAY 03 사람
    "baby": "The baby is very small.",
    "child": "The child plays with a ball.",
    "teenager": "My sister is a teenager.",
    "adult": "An adult reads this book.",
    "girl": "The girl has long hair.",
    "woman": "The woman is my mother.",
    "boy": "The boy runs very fast.",
    "man": "The man is my father.",
    "people": "Many people are here.",
    # ---------------- DAY 04 생일
    "birthday": "Today is my birthday.",
    "party": "We have a birthday party.",
    "balloon": "The balloon is red.",
    "candle": "I see one candle.",
    "gift": "I open my gift.",
    "card": "I write a card.",
    "camera": "My camera is very small.",
    # ---------------- DAY 05 감각
    "see": "I see a big bird.",
    "look": "I look at the sky.",
    "hear": "I hear a song.",
    "listen": "I listen to my teacher.",
    "smell": "I smell the flowers.",
    "taste": "I taste the soup.",
    "touch": "I touch my nose.",
    "feel": "I feel very happy.",
    # ---------------- DAY 06 움직임
    "open": "I open the window.",
    "close": "I close my book.",
    "push": "I push the heavy door.",
    "pull": "I pull the rope.",
    "enter": "I enter the classroom.",
    "come": "Come to my house.",
    "stop": "The bus stops here.",
    "move": "I move the chair.",
    # ---------------- DAY 07 하루 동작
    "have": "I have two brothers.",
    "eat": "I eat bread and milk.",
    "drink": "I drink juice every day.",
    "wash": "I wash my face.",
    "sleep": "I sleep for eight hours.",
    "talk": "I talk with my friend.",
    "smile": "I smile at my mother.",
    "cry": "The baby does not cry.",
    "shout": "Do not shout here.",
    # ---------------- DAY 08 공부
    "learn": "I learn new words.",
    "study": "I study every day.",
    "know": "I know your name.",
    "read": "I read a long book.",
    "write": "I write with a pencil.",
    "play": "I play with my friends.",
    "ask": "I ask my teacher.",
    "answer": "I know the answer.",
    # ---------------- DAY 09 미술
    "paint": "I paint a green tree.",
    "brush": "My brush is very small.",
    "sketchbook": "My sketchbook is new.",
    "draw": "I draw a big house.",
    "picture": "This picture is beautiful.",
    "crayon": "My crayon is red.",
    "make": "I make a paper boat.",
    "cut": "I cut the paper.",
    "paper": "I need one paper.",
    # ---------------- DAY 10 운동
    "soccer": "I play soccer after school.",
    "baseball": "My brother likes baseball.",
    "basketball": "We play basketball together.",
    "tennis": "I play tennis with my dad.",
    "badminton": "Badminton is very fun.",
    "sports": "I like all sports.",
    "win": "We win the game.",
    "lose": "We do not lose today.",
    # ---------------- DAY 11 음악
    "guitar": "I play the guitar.",
    "drum": "My drum is very loud.",
    "piano": "She plays the piano.",
    "cello": "The cello is very big.",
    "violin": "My violin is small.",
    "stage": "I stand on the stage.",
    "ticket": "I have two tickets.",
    "concert": "We go to a concert.",
    # ---------------- DAY 12 위치
    "in": "My book is in the bag.",
    "on": "The cup is on the table.",
    "under": "My shoes are under the bed.",
    "in front of": "I stand in front of you.",
    "behind": "The cat is behind the door.",
    "next to": "I sit next to my friend.",
    "between": "I am between mom and dad.",
    "over": "The bird flies over my house.",
    # ---------------- DAY 13 집
    "house": "My house is very big.",
    "garden": "Our garden has many flowers.",
    "bedroom": "My bedroom is small.",
    "bathroom": "The bathroom is very clean.",
    "kitchen": "My mother is in the kitchen.",
    "living room": "We watch TV in the living room.",
    "floor": "I sit on the floor.",
    "wall": "The wall is white.",
    # ---------------- DAY 14 가구
    "table": "The table is very long.",
    "sofa": "I sleep on the sofa.",
    "carpet": "Our carpet is soft.",
    "curtain": "The curtain is blue.",
    "mirror": "I look in the mirror.",
    "lamp": "My lamp is very bright.",
    "television": "I watch television at night.",
    "computer": "My computer is new.",
    "telephone": "The telephone is on the desk.",
    # ---------------- DAY 15 식사
    "breakfast": "I eat breakfast at seven.",
    "lunch": "I have lunch at school.",
    "dinner": "We eat dinner together.",
    "snack": "I want a small snack.",
    "cup": "My cup is yellow.",
    "plate": "The plate is very clean.",
    "spoon": "I eat with a spoon.",
    "fork": "My fork is small.",
    "knife": "The knife is very sharp.",
    # ---------------- DAY 16 간식
    "salt": "I do not want salt.",
    "sugar": "Sugar is very sweet.",
    "butter": "I put butter on bread.",
    "jam": "I like strawberry jam.",
    "biscuit": "I eat one biscuit.",
    "doughnut": "The doughnut is very sweet.",
    "pie": "My mother makes a pie.",
    "sandwich": "I eat a big sandwich.",
    "soda": "I do not drink soda.",
    "want": "I want a new book.",
    # ---------------- DAY 17 옷
    "put on": "I put on my coat.",
    "clothes": "My clothes are very clean.",
    "T-shirt": "My T-shirt is blue.",
    "pants": "These pants are too long.",
    "skirt": "Her skirt is pink.",
    "dress": "My sister has a new dress.",
    "coat": "My coat is very warm.",
    "jacket": "This jacket is too big.",
    # ---------------- DAY 18 착용
    "wear": "I wear a school cap.",
    "cap": "My cap is black.",
    "hat": "Her hat is very pretty.",
    "ring": "My mother has a gold ring.",
    "watch": "My watch is very old.",
    "glasses": "I wear glasses at school.",
    "mask": "I put on my mask.",
    "socks": "My socks are white.",
    "shoes": "My shoes are too small.",
    # ---------------- DAY 19 성격
    "kind": "She is a kind girl.",
    "smart": "My sister is very smart.",
    "brave": "The boy is very brave.",
    "quiet": "The classroom is quiet.",
    "funny": "My friend is very funny.",
    "shy": "I am shy at school.",
    "honest": "He is an honest boy.",
    "busy": "My father is very busy.",
    "lazy": "My cat is very lazy.",
    # ---------------- DAY 20 생김새
    "beautiful": "My mother is beautiful.",
    "handsome": "My brother is handsome.",
    "cute": "The puppy is very cute.",
    "tall": "This tree is very tall.",
    "pretty": "Her dress is pretty.",
    "ugly": "The old bag is ugly.",
    "young": "My aunt is very young.",
    # ---------------- DAY 21 숫자 11~20
    "eleven": "I have eleven crayons.",
    "twelve": "I am twelve years old.",
    "thirteen": "My sister is thirteen.",
    "fourteen": "I read fourteen books.",
    "fifteen": "I wait fifteen minutes.",
    "sixteen": "My brother is sixteen.",
    "seventeen": "She is seventeen years old.",
    "eighteen": "My cousin is eighteen.",
    "nineteen": "I count to nineteen.",
    "twenty": "I have twenty pencils.",
    # ---------------- DAY 22 숫자·셈
    "twenty-one": "My uncle is twenty-one.",
    "twenty-two": "We have twenty-two students.",
    "thirty": "My mother is thirty.",
    "forty": "My father is forty.",
    "fifty": "I count to fifty.",
    "zero": "The answer is zero.",
    "hundred": "I have one hundred stickers.",
    "thousand": "A thousand people are here.",
    "count": "I count my pencils.",
    "add": "I add two and three.",
    # ---------------- DAY 23 때
    "year": "I am eight years old.",
    "month": "We have twelve months.",
    "week": "We have seven days a week.",
    "date": "What is the date today?",
    "yesterday": "I read a book yesterday.",
    "today": "Today is a sunny day.",
    "tomorrow": "I go to school tomorrow.",
    # ---------------- DAY 24 요일
    "Monday": "I go to school on Monday.",
    "Tuesday": "I play tennis on Tuesday.",
    "Wednesday": "I study math on Wednesday.",
    "Thursday": "I have music on Thursday.",
    "Friday": "I meet my friend on Friday.",
    "Saturday": "I sleep late on Saturday.",
    "Sunday": "I eat out on Sunday.",
    "weekend": "I love the weekend.",
}
