# -*- coding: utf-8 -*-
"""뜯어먹는 1800 DAY 36~45 예문·동의어·반의어. english: (example, synonyms, antonyms)"""
DATA = {
    # ---------------- DAY 36
    "manager": ("The manager checked our work.", "", ""),
    "shore": ("We walked along the shore.", "coast", ""),
    "sunrise": ("We watched the sunrise together.", "", "sunset"),
    "lighting": ("The lighting in this room is soft.", "", ""),
    "wire": ("Do not touch the electric wire.", "", ""),
    "stage": ("The singer stood on the stage.", "", ""),
    "zone": ("This is a school zone.", "area", ""),
    "height": ("What is the height of the tower?", "", ""),
    "prediction": ("His prediction came true.", "", ""),
    "marriage": ("Their marriage lasted fifty years.", "", ""),
    "period": ("This period of history is exciting.", "", ""),
    "claim": ("They claim the land is theirs.", "", ""),
    "deal": ("We made a good deal.", "", ""),
    "limit": ("The speed limit is sixty.", "", ""),
    "tap": ("She gave a light tap on the door.", "", ""),
    "spray": ("Spray some water on the plants.", "", ""),
    "weigh": ("How much do you weigh?", "", ""),
    "pray": ("They pray for world peace.", "", ""),
    "greet": ("We greet our teacher every morning.", "", ""),
    "chew": ("Chew your food slowly.", "", ""),
    "attract": ("Flowers attract many bees.", "", ""),
    "overcome": ("She will overcome her fear.", "", ""),
    "salty": ("The soup is too salty.", "", "sweet"),
    "southern": ("The southern coast is warm.", "", "northern"),
    "curious": ("Children are curious about everything.", "", ""),
    "humorous": ("His speech was humorous.", "funny", ""),
    "foolish": ("It was a foolish decision.", "stupid", "wise"),
    "greedy": ("The greedy man wanted more gold.", "", ""),
    "valuable": ("This ring is very valuable.", "precious", ""),
    "certainly": ("I will certainly help you.", "surely", ""),
    # ---------------- DAY 37
    "agent": ("A travel agent booked our flight.", "", ""),
    "politics": ("He has no interest in politics.", "", ""),
    "reality": ("The dream became a reality.", "", ""),
    "relationship": ("They have a close relationship.", "", ""),
    "role": ("She played the main role.", "part", ""),
    "theater": ("We saw a play at the theater.", "", ""),
    "performance": ("The performance lasted two hours.", "", ""),
    "reservation": ("I made a dinner reservation.", "", ""),
    "sightseeing": ("We went sightseeing in Rome.", "", ""),
    "path": ("A narrow path leads to the lake.", "", ""),
    "source": ("The sun is our main source of energy.", "", ""),
    "proof": ("Do you have any proof?", "evidence", ""),
    "term": ("The spring term begins in March.", "", ""),
    "net": ("The ball went over the net.", "", ""),
    "cast": ("His arm is in a cast.", "", ""),
    "trust": ("I trust my old friends.", "believe", ""),
    "crash": ("The two cars did not crash.", "", ""),
    "hatch": ("The eggs will hatch next week.", "", ""),
    "clap": ("The audience began to clap.", "", ""),
    "announce": ("They will announce the winner soon.", "", ""),
    "represent": ("These stars represent the fifty states.", "", ""),
    "devote": ("She will devote her life to music.", "", ""),
    "peaceful": ("The village is quiet and peaceful.", "calm", ""),
    "painful": ("The injection was painful.", "", ""),
    "sharp": ("Be careful with the sharp knife.", "", "dull"),
    "responsible": ("You are responsible for your dog.", "", ""),
    "lazy": ("A lazy student never studies.", "", "diligent"),
    "likely": ("It is likely to rain today.", "", ""),
    "completely": ("The work is completely finished.", "", ""),
    "immediately": ("Come here immediately.", "", ""),
    # ---------------- DAY 38
    "architect": ("The architect designed a tall tower.", "", ""),
    "narrator": ("The narrator explained the story.", "", ""),
    "enemy": ("He treats nobody as an enemy.", "", "friend"),
    "throat": ("My throat hurts when I swallow.", "", ""),
    "illness": ("A long illness kept him home.", "disease", ""),
    "weed": ("Pull out the weed from the garden.", "", ""),
    "humor": ("She has a good sense of humor.", "", ""),
    "volcano": ("The volcano erupted last year.", "", ""),
    "kingdom": ("The kingdom was rich and strong.", "", ""),
    "attempt": ("His first attempt failed.", "try", ""),
    "award": ("She received a special award.", "prize", ""),
    "broadcast": ("They broadcast the game live.", "", ""),
    "aid": ("They sent aid to the flooded town.", "help", ""),
    "nod": ("He gave a small nod.", "", ""),
    "escape": ("The bird tried to escape.", "", ""),
    "envy": ("I envy your good memory.", "", ""),
    "measure": ("Measure the length of the desk.", "", ""),
    "chief": ("The chief reason is money.", "main", ""),
    "total": ("The total cost was fifty dollars.", "", ""),
    "worth": ("This book is worth reading.", "value", ""),
    "embarrass": ("Do not embarrass your friend.", "", ""),
    "erupt": ("The volcano may erupt again.", "", ""),
    "perform": ("They will perform on stage tonight.", "", ""),
    "publish": ("He will publish his first novel.", "", ""),
    "silent": ("The whole room was silent.", "quiet", ""),
    "silly": ("That was a silly question.", "foolish", ""),
    "scary": ("The movie was too scary.", "frightening", ""),
    "sore": ("I have a sore throat.", "", ""),
    "bitter": ("This coffee tastes bitter.", "", "sweet"),
    "lately": ("I have not seen him lately.", "recently", ""),
    # ---------------- DAY 39
    "landscape": ("The landscape changes in autumn.", "scenery", ""),
    "construction": ("The construction will take a year.", "", ""),
    "mood": ("She is in a good mood today.", "", ""),
    "excitement": ("The children shouted with excitement.", "", ""),
    "complaint": ("The shop received a complaint.", "", ""),
    "confidence": ("He speaks with confidence.", "", ""),
    "invasion": ("The invasion started at dawn.", "", ""),
    "container": ("Put the rice in a plastic container.", "", ""),
    "ash": ("Gray ash covered the ground.", "", ""),
    "bar": ("A metal bar blocks the gate.", "", ""),
    "contact": ("Please contact me by email.", "", ""),
    "benefit": ("Daily walking is a great benefit.", "", ""),
    "damage": ("The storm did great damage.", "harm", ""),
    "supply": ("They supply water to the village.", "provide", "demand"),
    "demand": ("The demand for masks grew fast.", "", "supply"),
    "lack": ("Plants die from a lack of water.", "", ""),
    "conflict": ("The conflict lasted many years.", "", ""),
    "spin": ("The wheels spin very fast.", "", ""),
    "scratch": ("Do not scratch the new table.", "", ""),
    "suppose": ("I suppose he is right.", "guess", ""),
    "refer": ("Please refer to page ten.", "", ""),
    "ruin": ("Rain will ruin our picnic.", "destroy", ""),
    "rid": ("We must rid the yard of weeds.", "", ""),
    "tight": ("These shoes are too tight.", "", "loose"),
    "brilliant": ("She had a brilliant idea.", "", ""),
    "specific": ("Give me a specific example.", "", ""),
    "unusual": ("That is an unusual name.", "strange", "common"),
    "negative": ("Do not be so negative.", "", "positive"),
    "royal": ("The royal family lives here.", "", ""),
    "partly": ("The sky is partly cloudy.", "", ""),
    # ---------------- DAY 40
    "happiness": ("Money cannot buy happiness.", "", "sadness"),
    "freedom": ("Everyone wants freedom.", "liberty", ""),
    "independence": ("The country won its independence.", "", ""),
    "imagination": ("Children have rich imagination.", "", ""),
    "importance": ("We know the importance of sleep.", "", ""),
    "speech": ("His speech moved the audience.", "", ""),
    "silence": ("A long silence followed.", "", "noise"),
    "invitation": ("Thank you for your invitation.", "", ""),
    "exhibition": ("The art exhibition opens Monday.", "", ""),
    "sculpture": ("The sculpture is made of stone.", "", ""),
    "region": ("This region grows apples.", "area", ""),
    "position": ("Change your position if you are tired.", "", ""),
    "research": ("They research new medicines.", "study", ""),
    "aim": ("Our aim is to win the contest.", "goal", ""),
    "moral": ("The story has a clear moral.", "", ""),
    "extra": ("I need an extra chair.", "", ""),
    "arrange": ("Please arrange the chairs in rows.", "", ""),
    "advise": ("My teacher will advise me.", "", ""),
    "recommend": ("Can you recommend a good book?", "", ""),
    "declare": ("They will declare the results tonight.", "announce", ""),
    "prove": ("Can you prove your story?", "", ""),
    "injure": ("Careless play can injure you.", "hurt", ""),
    "connect": ("Connect the printer to the computer.", "", ""),
    "hug": ("She gave her mother a warm hug.", "", ""),
    "foggy": ("The morning was cold and foggy.", "", ""),
    "neat": ("Her desk is always neat.", "tidy", "messy"),
    "loose": ("This button is loose.", "", "tight"),
    "endangered": ("Tigers are an endangered animal.", "", ""),
    "bound": ("This train is bound for Busan.", "", ""),
    "recently": ("I recently moved to a new house.", "lately", ""),
    # ---------------- DAY 41
    "merchant": ("The merchant sold silk and tea.", "", ""),
    "heritage": ("This temple is a world heritage site.", "", ""),
    "organization": ("She works for a green organization.", "", ""),
    "kindergarten": ("My sister goes to kindergarten.", "", ""),
    "management": ("Good management saves money.", "", ""),
    "operation": ("The operation took three hours.", "", ""),
    "mission": ("Their mission was to find water.", "", ""),
    "means": ("A bike is a cheap means of travel.", "", ""),
    "payment": ("The payment is due today.", "", ""),
    "merit": ("The main merit of this plan is speed.", "", ""),
    "mirror": ("She looked into the mirror.", "", ""),
    "ladder": ("He climbed up the ladder.", "", ""),
    "ingredient": ("Sugar is the main ingredient.", "", ""),
    "index": ("Check the index at the back.", "", ""),
    "behave": ("Please behave well at the party.", "act", ""),
    "compete": ("Ten teams will compete today.", "", ""),
    "argue": ("Do not argue with your parents.", "", "agree"),
    "release": ("They will release the bird tomorrow.", "free", ""),
    "pretend": ("Do not pretend to be sick.", "", ""),
    "conclude": ("Let us conclude the meeting now.", "", ""),
    "observe": ("Observe the moon through this glass.", "watch", ""),
    "spicy": ("Korean food is often spicy.", "hot", ""),
    "terrific": ("You did a terrific job.", "great", ""),
    "steady": ("He made steady progress.", "", ""),
    "various": ("The shop sells various hats.", "", ""),
    "unique": ("Every fingerprint is unique.", "", "common"),
    "unnecessary": ("Cut the unnecessary words.", "", "necessary"),
    "ill": ("She has been ill for a week.", "sick", "healthy"),
    "underground": ("The train runs underground.", "", ""),
    "sincerely": ("I sincerely thank you.", "", ""),
    # ---------------- DAY 42
    "peer": ("A peer can help you study.", "", ""),
    "pressure": ("He works well under pressure.", "", ""),
    "loss": ("The loss of his dog made him sad.", "", "gain"),
    "playground": ("Children run in the playground.", "", ""),
    "pond": ("Ducks swim in the pond.", "", ""),
    "harbor": ("Ships rest in the harbor.", "port", ""),
    "frame": ("The photo has a wooden frame.", "", ""),
    "hammer": ("He hit the nail with a hammer.", "", ""),
    "expression": ("Her expression showed surprise.", "", ""),
    "quality": ("This cloth is of high quality.", "", ""),
    "movement": ("A sudden movement scared the bird.", "", ""),
    "package": ("A package arrived this morning.", "", ""),
    "survey": ("We did a survey about school lunch.", "", ""),
    "panic": ("Do not panic in an emergency.", "", ""),
    "sigh": ("She gave a deep sigh.", "", ""),
    "rinse": ("Rinse the dishes with warm water.", "", ""),
    "appeal": ("They appeal for more help.", "", ""),
    "sweep": ("Please sweep the floor.", "", ""),
    "consist": ("Our class consist of twenty students.", "", ""),
    "unify": ("The leader tried to unify the country.", "unite", ""),
    "depress": ("Cloudy days depress me.", "", ""),
    "blame": ("Do not blame others for your mistake.", "", ""),
    "smooth": ("The baby has smooth skin.", "", "rough"),
    "wooden": ("They sat on a wooden bench.", "", ""),
    "helpless": ("The tiny bird looked helpless.", "", ""),
    "incredible": ("The view was incredible.", "amazing", ""),
    "available": ("No seats are available now.", "", ""),
    "ancient": ("We studied ancient Egypt.", "", "modern"),
    "recent": ("This is a recent photo.", "", "old"),
    "thus": ("It rained. Thus, the game stopped.", "therefore", ""),
    # ---------------- DAY 43
    "wildlife": ("This park protects wildlife.", "", ""),
    "sunset": ("The sunset painted the sky red.", "", "sunrise"),
    "horizon": ("The sun sank below the horizon.", "", ""),
    "steam": ("Hot steam rose from the pot.", "", ""),
    "warmth": ("We felt the warmth of the fire.", "", ""),
    "statement": ("The police read his statement.", "", ""),
    "response": ("Her response was very quick.", "answer", ""),
    "task": ("This task is not easy.", "job", ""),
    "security": ("Airport security is very strict.", "", ""),
    "needle": ("She threaded the needle.", "", ""),
    "branch": ("A bird sat on the branch.", "", ""),
    "thread": ("I need black thread.", "", ""),
    "row": ("We sat in the front row.", "line", ""),
    "yawn": ("A long yawn showed he was tired.", "", ""),
    "rub": ("Do not rub your eyes.", "", ""),
    "wipe": ("Wipe the table after dinner.", "", ""),
    "operate": ("Can you operate this machine?", "", ""),
    "contain": ("These cans contain fresh juice.", "", ""),
    "preserve": ("We must preserve old buildings.", "protect", "destroy"),
    "refuse": ("She will refuse the offer.", "", "accept"),
    "remind": ("Please remind me about the meeting.", "", ""),
    "bother": ("Do not bother your sister.", "", ""),
    "tiny": ("A tiny insect sat on the leaf.", "", "huge"),
    "curly": ("She has long curly hair.", "", "straight"),
    "rapid": ("The river has a rapid flow.", "fast", "slow"),
    "shy": ("The shy boy said nothing.", "", ""),
    "eastern": ("The eastern sky grew bright.", "", "western"),
    "violent": ("Violent games are not for children.", "", ""),
    "worldwide": ("The song became a worldwide hit.", "global", ""),
    "highly": ("The book is highly useful.", "", ""),
    # ---------------- DAY 44
    "dinosaur": ("A dinosaur bone was found here.", "", ""),
    "ruler": ("The ruler governed for thirty years.", "", ""),
    "admiral": ("The admiral led the fleet.", "", ""),
    "liberty": ("They fought for liberty.", "freedom", ""),
    "tragedy": ("The war was a great tragedy.", "", "comedy"),
    "trial": ("The trial begins next Monday.", "", ""),
    "treatment": ("He needs medical treatment.", "", ""),
    "shelter": ("They built a shelter from branches.", "", ""),
    "orphanage": ("We sent gifts to the orphanage.", "", ""),
    "item": ("Every item is on sale.", "", ""),
    "gravity": ("Gravity pulls things to the ground.", "", ""),
    "clue": ("The police found an important clue.", "hint", ""),
    "range": ("The price range is wide.", "", ""),
    "rumor": ("Do not believe that rumor.", "", ""),
    "vehicle": ("No vehicle can enter this street.", "", ""),
    "sew": ("She can sew her own clothes.", "", ""),
    "associate": ("We associate spring with flowers.", "", ""),
    "identify": ("Can you identify this bird?", "", ""),
    "mention": ("He did not mention the accident.", "", ""),
    "establish": ("They will establish a new school.", "found", ""),
    "unite": ("The two clubs will unite.", "", "divide"),
    "frustrate": ("Slow internet can frustrate anyone.", "", ""),
    "stuck": ("The car got stuck in the mud.", "", ""),
    "cheerful": ("She has a cheerful smile.", "", ""),
    "careless": ("A careless driver caused the crash.", "", "careful"),
    "dull": ("The lecture was rather dull.", "boring", ""),
    "disgusting": ("The smell was disgusting.", "", ""),
    "willing": ("She is willing to help us.", "", ""),
    "golden": ("The field looked golden at sunset.", "", ""),
    "apart": ("The two houses stand far apart.", "", "together"),
    # ---------------- DAY 45
    "lung": ("Smoking damages the lung.", "", ""),
    "passport": ("Do not lose your passport.", "", ""),
    "photo": ("Let me take a photo of you.", "picture", ""),
    "envelope": ("Put the letter in an envelope.", "", ""),
    "attendant": ("The flight attendant brought water.", "", ""),
    "appointment": ("I have a dental appointment.", "", ""),
    "midnight": ("The party ended at midnight.", "", "noon"),
    "personality": ("She has a bright personality.", "character", ""),
    "chimney": ("Smoke rose from the chimney.", "", ""),
    "fence": ("A white fence surrounds the yard.", "", ""),
    "evidence": ("There is no evidence of a fire.", "proof", ""),
    "feature": ("The main feature is the big window.", "", ""),
    "flavor": ("This ice cream has a fruit flavor.", "taste", ""),
    "leap": ("The cat made a great leap.", "jump", ""),
    "leak": ("Water began to leak from the pipe.", "", ""),
    "scream": ("Do not scream in the hallway.", "shout", ""),
    "refresh": ("A short nap will refresh you.", "", ""),
    "occur": ("Accidents occur on rainy days.", "happen", ""),
    "obtain": ("You can obtain a ticket online.", "get", ""),
    "intend": ("I intend to study abroad.", "", ""),
    "lower": ("Please lower your voice.", "", "raise"),
    "lean": ("Do not lean on the door.", "", ""),
    "equal": ("All students are equal here.", "same", ""),
    "separate": ("They sleep in separate rooms.", "", ""),
    "spare": ("Do you have a spare pen?", "extra", ""),
    "hard-working": ("She is a hard-working student.", "diligent", "lazy"),
    "hopeless": ("The situation is not hopeless.", "", ""),
    "raw": ("Some people eat raw fish.", "", "cooked"),
    "portable": ("This is a portable speaker.", "", ""),
    "rarely": ("He rarely eats meat.", "seldom", "often"),
}
