# -*- coding: utf-8 -*-
"""뜯어먹는 1800 DAY 01~05 예문·동의어·반의어.
스타일은 뜯어먹는 1200에 맞춤 — 4~8단어의 짧은 중학 수준 문장, 표제어는 원형 그대로.
동의/반의는 중학생이 헷갈리지 않을 확실한 것만.
"""

# english: (example, synonyms, antonyms)
DATA = {
    # ---------------- DAY 01
    "life": ("She has a happy life.", "", "death"),
    "person": ("He is a kind person.", "", ""),
    "job": ("My father has a new job.", "work", ""),
    "earth": ("The earth goes around the sun.", "", ""),
    "country": ("Korea is a beautiful country.", "nation", ""),
    "way": ("Please show me the way.", "", ""),
    "story": ("She told me a funny story.", "tale", ""),
    "movie": ("We watched a movie last night.", "film", ""),
    "problem": ("We solved the math problem.", "", "solution"),
    "lot": ("I have a lot of homework.", "", ""),
    "hand": ("He raised his hand slowly.", "", ""),
    "place": ("This is a quiet place.", "spot", ""),
    "call": ("Please call me tonight.", "", ""),
    "start": ("Let us start the game.", "begin", "finish"),
    "try": ("I will try again tomorrow.", "attempt", ""),
    "use": ("May I use your pen?", "", ""),
    "kind": ("She is very kind to me.", "nice", "mean"),
    "fun": ("The party was really fun.", "", "boring"),
    "future": ("I dream about my future.", "", "past"),
    "have": ("I have a new bike.", "", ""),
    "make": ("Let us make a cake.", "create", ""),
    "let": ("Please let me go now.", "allow", ""),
    "get": ("I want to get a new book.", "", ""),
    "take": ("Please take an umbrella.", "", "give"),
    "different": ("We have different ideas.", "", "same"),
    "important": ("Sleep is very important.", "", ""),
    "right": ("Your answer is right.", "correct", "wrong"),
    "sure": ("I am sure about the answer.", "certain", ""),
    "well": ("She sings very well.", "", ""),
    "hard": ("The test was very hard.", "difficult", "easy"),
    # ---------------- DAY 02
    "piece": ("I ate a piece of cake.", "", ""),
    "example": ("Give me an example, please.", "", ""),
    "minute": ("Please wait for one minute.", "", ""),
    "trip": ("We took a trip to Busan.", "journey", ""),
    "letter": ("I wrote a letter to my friend.", "", ""),
    "language": ("English is a world language.", "", ""),
    "science": ("Science is my favorite subject.", "", ""),
    "fire": ("The fire burned all night.", "", ""),
    "name": ("My name is Jimin.", "", ""),
    "part": ("This is the best part.", "piece", "whole"),
    "plan": ("We made a plan for summer.", "", ""),
    "plant": ("The plant needs more water.", "", ""),
    "practice": ("I practice the piano every day.", "", ""),
    "turn": ("It is your turn now.", "", ""),
    "need": ("I need your help.", "", ""),
    "learn": ("We learn English at school.", "", "teach"),
    "keep": ("Please keep the door open.", "", ""),
    "find": ("I cannot find my key.", "", "lose"),
    "become": ("She wants to become a doctor.", "", ""),
    "live": ("They live near the park.", "", "die"),
    "mean": ("What does this word mean?", "", ""),
    "last": ("This is my last chance.", "final", "first"),
    "any": ("Do you have any questions?", "", ""),
    "each": ("Each student has a book.", "every", ""),
    "other": ("The other side is quiet.", "", ""),
    "another": ("I want another cup of tea.", "", ""),
    "same": ("We go to the same school.", "", "different"),
    "too": ("This bag is too heavy.", "", ""),
    "also": ("She also likes music.", "", ""),
    "really": ("I really enjoyed the movie.", "", ""),
    # ---------------- DAY 03
    "restaurant": ("We ate at a new restaurant.", "", ""),
    "street": ("The street is very busy.", "road", ""),
    "side": ("Please sit on this side.", "", ""),
    "space": ("There is no space for my bag.", "room", ""),
    "art": ("I love my art class.", "", ""),
    "culture": ("Korean culture is interesting.", "", ""),
    "activity": ("Swimming is my favorite activity.", "", ""),
    "weekend": ("I read books on the weekend.", "", ""),
    "information": ("I need more information.", "", ""),
    "face": ("Wash your face every morning.", "", ""),
    "mind": ("She changed her mind.", "", ""),
    "work": ("My parents work in a hospital.", "job", ""),
    "watch": ("We watch TV after dinner.", "", ""),
    "worry": ("Do not worry about the test.", "", ""),
    "change": ("I want to change my seat.", "", ""),
    "light": ("The room has bright light.", "", "dark"),
    "present": ("I got a present for my birthday.", "gift", ""),
    "middle": ("He sat in the middle.", "center", ""),
    "favorite": ("Blue is my favorite color.", "", ""),
    "enjoy": ("I enjoy playing soccer.", "", ""),
    "win": ("Our team will win the game.", "", "lose"),
    "understand": ("I understand your question.", "", ""),
    "warm": ("The soup is still warm.", "", "cold"),
    "clean": ("Keep your room clean.", "", "dirty"),
    "own": ("I have my own room.", "", ""),
    "interesting": ("This book is very interesting.", "", "boring"),
    "famous": ("He is a famous singer.", "", ""),
    "special": ("Today is a special day.", "", ""),
    "fast": ("That car is very fast.", "quick", "slow"),
    "only": ("I have only one pencil.", "", ""),
    # ---------------- DAY 04
    "clothes": ("I bought new clothes.", "", ""),
    "poem": ("She wrote a short poem.", "", ""),
    "nature": ("We should protect nature.", "", ""),
    "forest": ("Many animals live in the forest.", "", ""),
    "island": ("Jeju is a beautiful island.", "", ""),
    "village": ("My grandmother lives in a small village.", "", "city"),
    "state": ("Texas is a large state.", "", ""),
    "habit": ("Reading is a good habit.", "", ""),
    "history": ("I like my history class.", "", ""),
    "dialog(ue)": ("We practiced the dialog in class.", "", ""),
    "newspaper": ("My father reads the newspaper.", "", ""),
    "vacation": ("We go to the beach on vacation.", "holiday", ""),
    "store": ("The store opens at nine.", "shop", ""),
    "sound": ("I heard a strange sound.", "noise", ""),
    "point": ("That is a good point.", "", ""),
    "land": ("The plane will land soon.", "", ""),
    "fall": ("Leaves fall in autumn.", "", "rise"),
    "fly": ("Birds fly over the river.", "", ""),
    "visit": ("We visit our grandparents every month.", "", ""),
    "begin": ("The class will begin soon.", "start", "end"),
    "grow": ("Plants grow in the sun.", "", ""),
    "believe": ("I believe your story.", "", ""),
    "save": ("I save money every month.", "", "spend"),
    "participate": ("Many students participate in the contest.", "join", ""),
    "please": ("Please close the window.", "", ""),
    "easy": ("The question was very easy.", "simple", "hard"),
    "poor": ("The poor family needs help.", "", "rich"),
    "such": ("I never saw such a big dog.", "", ""),
    "just": ("I just finished my homework.", "", ""),
    "always": ("She is always kind to me.", "", "never"),
    # ---------------- DAY 05
    "war": ("Many people died in the war.", "", "peace"),
    "soldier": ("The soldier stood at the gate.", "", ""),
    "vegetable": ("A carrot is a healthy vegetable.", "", ""),
    "leaf": ("A yellow leaf fell down.", "", ""),
    "bottle": ("I drank a bottle of water.", "", ""),
    "machine": ("This machine washes clothes.", "", ""),
    "area": ("This area is very quiet.", "", ""),
    "grade": ("I got a good grade.", "", ""),
    "advertisement[ad]": ("I saw the advertisement on TV.", "", ""),
    "spring": ("Flowers bloom in spring.", "", ""),
    "rock": ("A big rock blocked the road.", "stone", ""),
    "line": ("Please draw a straight line.", "", ""),
    "exercise": ("I exercise every morning.", "", ""),
    "cook": ("My mother will cook dinner.", "", ""),
    "stay": ("We will stay at a hotel.", "", "leave"),
    "break": ("Do not break the window.", "", "fix"),
    "front": ("He sat in the front seat.", "", "back"),
    "second": ("Please wait a second.", "", ""),
    "cold": ("The water is very cold.", "", "hot"),
    "happen": ("What will happen next?", "", ""),
    "leave": ("We leave home at eight.", "", "stay"),
    "remember": ("I remember your name.", "", "forget"),
    "wear": ("I wear a school uniform.", "", ""),
    "move": ("Please move your chair.", "", ""),
    "send": ("I will send you an email.", "", "receive"),
    "large": ("They live in a large house.", "big", "small"),
    "amazing": ("The show was amazing.", "", ""),
    "early": ("I woke up early today.", "", "late"),
    "often": ("We often play together.", "", ""),
    "sometimes": ("I sometimes walk to school.", "", ""),
}
