# -*- coding: utf-8 -*-
"""뜯어먹는 1800 DAY 16~25 예문·동의어·반의어. english: (example, synonyms, antonyms)"""
DATA = {
    # ---------------- DAY 16
    "planet": ("Mars is a red planet.", "", ""),
    "beauty": ("The beauty of the lake amazed us.", "", ""),
    "sight": ("The old man lost his sight.", "", ""),
    "nation": ("Our nation has a long history.", "country", ""),
    "foreigner": ("A foreigner asked me for directions.", "", ""),
    "band": ("My brother plays in a band.", "", ""),
    "straw": ("She drinks juice with a straw.", "", ""),
    "storm": ("The storm broke many trees.", "", ""),
    "disease": ("This disease spreads very fast.", "illness", ""),
    "purpose": ("What is the purpose of this trip?", "", ""),
    "display": ("They display new phones in the store.", "show", ""),
    "reply": ("Please reply to my email.", "answer", ""),
    "record": ("She will record her voice.", "", ""),
    "cheer": ("We cheer for our team.", "", ""),
    "shake": ("Shake the bottle before drinking.", "", ""),
    "key": ("I lost my house key.", "", ""),
    "wild": ("Wild animals live in the forest.", "", ""),
    "square": ("Draw a small square here.", "", ""),
    "wake": ("I wake up at six every day.", "", ""),
    "discover": ("They will discover a new star.", "find", ""),
    "solve": ("Can you solve this problem?", "", ""),
    "continue": ("Please continue your story.", "", "stop"),
    "burn": ("Dry leaves burn easily.", "", ""),
    "simple": ("The rule is very simple.", "easy", ""),
    "quiet": ("The library is very quiet.", "silent", "loud"),
    "traditional": ("Hanbok is a traditional dress.", "", "modern"),
    "international": ("This is an international airport.", "", ""),
    "huge": ("They live in a huge house.", "", "tiny"),
    "instead": ("I drank tea instead of coffee.", "", ""),
    "suddenly": ("The door suddenly opened.", "", ""),
    # ---------------- DAY 17
    "bridge": ("We walked across the bridge.", "", ""),
    "ghost": ("Nobody believes in that ghost.", "", ""),
    "scene": ("The last scene was sad.", "", ""),
    "effort": ("Your effort will be rewarded.", "", ""),
    "wisdom": ("Old people have deep wisdom.", "", ""),
    "fault": ("The accident was my fault.", "", ""),
    "flight": ("Our flight leaves at noon.", "", ""),
    "zoo": ("We saw lions at the zoo.", "", ""),
    "candle": ("She lit a small candle.", "", ""),
    "bottom": ("The key sank to the bottom.", "", "top"),
    "mistake": ("Everyone can make a mistake.", "error", ""),
    "trouble": ("He is in big trouble.", "", ""),
    "nap": ("I take a short nap after lunch.", "", ""),
    "blow": ("The wind will blow all night.", "", ""),
    "flood": ("The flood damaged many houses.", "", ""),
    "hurry": ("Please hurry or we will be late.", "rush", ""),
    "treat": ("Please treat animals kindly.", "", ""),
    "express": ("I cannot express my feelings.", "", ""),
    "breathe": ("It is hard to breathe here.", "", ""),
    "hate": ("I hate rainy mornings.", "", "love"),
    "create": ("Artists create beautiful things.", "make", ""),
    "divide": ("Divide the cake into six pieces.", "", ""),
    "soft": ("This pillow is very soft.", "", "hard"),
    "empty": ("The bottle is empty.", "", "full"),
    "perfect": ("Your answer is perfect.", "", ""),
    "successful": ("She is a successful writer.", "", ""),
    "everyday": ("Reading is my everyday habit.", "", ""),
    "low": ("The chair is too low.", "", "high"),
    "alone": ("He lives alone in the city.", "", ""),
    "inside": ("Please wait inside the room.", "", "outside"),
    # ---------------- DAY 18
    "creature": ("A whale is a huge creature.", "", ""),
    "army": ("His brother joined the army.", "", ""),
    "society": ("We all live in a society.", "", ""),
    "fan": ("I am a big fan of that singer.", "", ""),
    "wheel": ("The front wheel is broken.", "", ""),
    "pair": ("I bought a pair of shoes.", "", ""),
    "joy": ("Her face was full of joy.", "", "sorrow"),
    "memory": ("I have a happy memory of that day.", "", ""),
    "recipe": ("This recipe is very easy.", "", ""),
    "kid": ("The kid is playing outside.", "child", ""),
    "smoke": ("Black smoke came from the roof.", "", ""),
    "favor": ("May I ask you a favor?", "", ""),
    "trick": ("He showed us a card trick.", "", ""),
    "experiment": ("We did a science experiment.", "", ""),
    "drop": ("Do not drop the glass.", "", ""),
    "press": ("Press this button to start.", "push", ""),
    "stick": ("The stamp will stick to the paper.", "", ""),
    "roll": ("The ball will roll down the hill.", "", ""),
    "throw": ("Do not throw stones.", "", "catch"),
    "serve": ("They serve breakfast at seven.", "", ""),
    "improve": ("I want to improve my English.", "", ""),
    "realize": ("I did not realize my mistake.", "", ""),
    "dry": ("The towel is already dry.", "", "wet"),
    "complete": ("Please complete this form.", "finish", ""),
    "lucky": ("You are very lucky today.", "", "unlucky"),
    "natural": ("This juice has a natural taste.", "", ""),
    "friendly": ("Our new teacher is friendly.", "kind", ""),
    "cute": ("The puppy is so cute.", "", ""),
    "already": ("She has already left.", "", ""),
    "especially": ("I like fruit, especially apples.", "", ""),
    # ---------------- DAY 19
    "hometown": ("My hometown is a small city.", "", ""),
    "yard": ("The children play in the yard.", "", ""),
    "grocery": ("Mom went to the grocery store.", "", ""),
    "fairy": ("She read a fairy tale.", "", ""),
    "flag": ("The flag waved in the wind.", "", ""),
    "manner": ("He answered in a kind manner.", "way", ""),
    "noise": ("The noise woke me up.", "sound", ""),
    "pain": ("I feel pain in my back.", "", ""),
    "danger": ("The sign warns of danger.", "", "safety"),
    "guide": ("The guide showed us the palace.", "", ""),
    "coach": ("Our coach is very strict.", "", ""),
    "note": ("She left a short note.", "", ""),
    "count": ("Count the students, please.", "", ""),
    "sail": ("They sail across the ocean.", "", ""),
    "promise": ("I promise to help you.", "", ""),
    "repeat": ("Please repeat the question.", "", ""),
    "bake": ("Let us bake some cookies.", "", ""),
    "gather": ("We gather in the hall at nine.", "collect", ""),
    "succeed": ("She will succeed in the exam.", "", "fail"),
    "protect": ("We must protect wild animals.", "", ""),
    "advertise": ("They advertise on television.", "", ""),
    "disappear": ("The moon will disappear soon.", "", "appear"),
    "electric": ("This is an electric car.", "", ""),
    "lovely": ("What a lovely garden!", "", ""),
    "thin": ("The ice is very thin.", "", "thick"),
    "round": ("The table is round.", "", ""),
    "deep": ("The river is very deep.", "", "shallow"),
    "wide": ("The road is quite wide.", "broad", "narrow"),
    "yet": ("She has not arrived yet.", "", ""),
    "quickly": ("He finished his lunch quickly.", "", "slowly"),
    # ---------------- DAY 20
    "couple": ("A couple sat by the window.", "", ""),
    "tourist": ("The tourist took many photos.", "", ""),
    "gate": ("Meet me at the school gate.", "", ""),
    "background": ("The background of the photo is dark.", "", ""),
    "capital": ("Seoul is the capital of Korea.", "", ""),
    "valley": ("A river runs through the valley.", "", ""),
    "direction": ("We walked in the wrong direction.", "", ""),
    "distance": ("The distance is about two miles.", "", ""),
    "behavior": ("His behavior surprised everyone.", "", ""),
    "dictionary": ("Look it up in the dictionary.", "", ""),
    "object": ("A strange object was in the sky.", "", ""),
    "rescue": ("They will rescue the lost dog.", "save", ""),
    "tear": ("A tear ran down her face.", "", ""),
    "honor": ("We honor our brave soldiers.", "", ""),
    "increase": ("Prices increase every year.", "", "decrease"),
    "bite": ("The dog will not bite you.", "", ""),
    "male": ("A male lion has long hair.", "", "female"),
    "native": ("She is a native speaker of English.", "", ""),
    "disappoint": ("I do not want to disappoint you.", "", ""),
    "shine": ("The stars shine at night.", "", ""),
    "fix": ("Can you fix my bike?", "repair", "break"),
    "pour": ("Please pour some water.", "", ""),
    "allow": ("They do not allow pets here.", "let", ""),
    "prevent": ("Wash your hands to prevent colds.", "", ""),
    "certain": ("I am certain about the date.", "sure", ""),
    "mental": ("Mental health is important.", "", "physical"),
    "comfortable": ("This chair is very comfortable.", "", ""),
    "expensive": ("That bag is too expensive.", "", "cheap"),
    "therefore": ("It rained. Therefore, we stayed home.", "", ""),
    "everywhere": ("Flowers were everywhere in the park.", "", ""),
    # ---------------- DAY 21
    "action": ("Words are easy, but action is hard.", "", ""),
    "talent": ("She has a talent for music.", "", ""),
    "choice": ("You made a wise choice.", "", ""),
    "slave": ("No one should live as a slave.", "", ""),
    "situation": ("The situation is getting better.", "", ""),
    "pride": ("He felt great pride in his son.", "", ""),
    "tip": ("Write your name at the tip.", "", ""),
    "stair": ("She sat on the bottom stair.", "", ""),
    "soil": ("This soil is good for plants.", "", ""),
    "master": ("He is a master of the guitar.", "", ""),
    "suit": ("My father wore a black suit.", "", ""),
    "notice": ("Did you notice her new hat?", "", ""),
    "bow": ("Please bow to your teacher.", "", ""),
    "rush": ("Do not rush your homework.", "hurry", ""),
    "adult": ("An adult ticket costs more.", "", "child"),
    "principal": ("Our principal gave a speech.", "", ""),
    "folk": ("We sang an old folk song.", "", ""),
    "material": ("Wood is a natural material.", "", ""),
    "standard": ("Her work is above the standard.", "", ""),
    "surf": ("They surf at the beach every summer.", "", ""),
    "accept": ("Please accept my apology.", "", "refuse"),
    "obey": ("We must obey the rules.", "", ""),
    "hide": ("Do not hide the truth.", "", ""),
    "basic": ("These are basic English words.", "", ""),
    "local": ("We shop at the local market.", "", ""),
    "boring": ("The lecture was very boring.", "", "interesting"),
    "weak": ("The old man is very weak.", "", "strong"),
    "quick": ("He gave a quick answer.", "fast", "slow"),
    "easily": ("She passed the test easily.", "", ""),
    "abroad": ("My uncle lives abroad.", "", ""),
    # ---------------- DAY 22
    "hero": ("The firefighter is a real hero.", "", ""),
    "ability": ("She has the ability to lead.", "", ""),
    "knowledge": ("Books give us knowledge.", "", ""),
    "technique": ("This technique is hard to learn.", "", ""),
    "floor": ("Do not sit on the cold floor.", "", ""),
    "cancer": ("Smoking can cause cancer.", "", ""),
    "diet": ("A balanced diet keeps you healthy.", "", ""),
    "garbage": ("Take out the garbage, please.", "trash", ""),
    "cash": ("I paid in cash.", "", ""),
    "countryside": ("The countryside is quiet and clean.", "", ""),
    "route": ("This route is the shortest.", "", ""),
    "amount": ("A large amount of snow fell.", "", ""),
    "score": ("The final score was three to two.", "", ""),
    "challenge": ("This job is a real challenge.", "", ""),
    "cure": ("Doctors hope to cure the disease.", "", ""),
    "appear": ("Stars appear after sunset.", "", "disappear"),
    "spread": ("The news will spread fast.", "", ""),
    "hunt": ("Lions hunt at night.", "", ""),
    "destroy": ("The fire will destroy the forest.", "", "build"),
    "consider": ("Please consider my idea.", "", ""),
    "expect": ("We expect good weather tomorrow.", "", ""),
    "suggest": ("May I suggest another plan?", "", ""),
    "cultural": ("We joined a cultural festival.", "", ""),
    "social": ("Social media is very popular.", "", ""),
    "elderly": ("Give your seat to elderly people.", "", ""),
    "unhappy": ("She looked unhappy this morning.", "", "happy"),
    "crazy": ("That is a crazy idea.", "", ""),
    "alive": ("The fish is still alive.", "", "dead"),
    "outside": ("The children are playing outside.", "", "inside"),
    "quite": ("The room is quite small.", "", ""),
    # ---------------- DAY 23
    "host": ("The host welcomed every guest.", "", "guest"),
    "audience": ("The audience clapped loudly.", "", ""),
    "athlete": ("An athlete trains every day.", "", ""),
    "cell": ("Every cell has its own job.", "", ""),
    "wing": ("The bird hurt its left wing.", "", ""),
    "tail": ("The dog wagged its tail.", "", ""),
    "bowl": ("I ate a bowl of soup.", "", ""),
    "brick": ("The wall is made of brick.", "", ""),
    "temperature": ("The temperature dropped last night.", "", ""),
    "transportation": ("Public transportation is cheap here.", "", ""),
    "site": ("This is the site of an old palace.", "", ""),
    "decision": ("It was a hard decision.", "", ""),
    "fiction": ("I enjoy science fiction.", "", ""),
    "frighten": ("Loud noises frighten my cat.", "scare", ""),
    "scare": ("Ghost stories scare little children.", "frighten", ""),
    "slip": ("Be careful not to slip.", "", ""),
    "melt": ("The snow will melt soon.", "", "freeze"),
    "pollute": ("Factories pollute the river.", "", ""),
    "affect": ("Weather can affect our mood.", "", ""),
    "depend": ("Children depend on their parents.", "", ""),
    "manage": ("She will manage the new shop.", "", ""),
    "fit": ("These shoes do not fit me.", "", ""),
    "correct": ("Your spelling is correct.", "right", "wrong"),
    "surprising": ("The result was surprising.", "", ""),
    "active": ("My grandmother is still active.", "", ""),
    "colorful": ("The garden is very colorful.", "", ""),
    "wet": ("My socks are wet.", "", "dry"),
    "lively": ("The market is lively in the morning.", "", ""),
    "daily": ("Exercise is part of my daily life.", "", ""),
    "straight": ("Go straight for two blocks.", "", ""),
    # ---------------- DAY 24
    "god": ("Many people pray to god.", "", ""),
    "guest": ("We had a guest for dinner.", "visitor", "host"),
    "diver": ("The diver went under the sea.", "", ""),
    "blood": ("Blood runs through our body.", "", ""),
    "pool": ("We swam in the pool.", "", ""),
    "temple": ("The old temple is on the hill.", "", ""),
    "thought": ("A good thought came to me.", "idea", ""),
    "crop": ("Rice is an important crop.", "", ""),
    "sheet": ("Give me a sheet of paper.", "", ""),
    "quarter": ("I ate a quarter of the pie.", "", ""),
    "crowd": ("A large crowd filled the square.", "", ""),
    "care": ("Take care of your health.", "", ""),
    "strike": ("Do not strike the desk.", "hit", ""),
    "relative": ("A relative visited us yesterday.", "", ""),
    "patient": ("The doctor helped the patient.", "", ""),
    "gain": ("You will gain weight if you eat late.", "", "lose"),
    "provide": ("The school will provide lunch.", "", ""),
    "dig": ("Dogs like to dig holes.", "", ""),
    "explore": ("We want to explore the cave.", "", ""),
    "warn": ("The sign will warn drivers.", "", ""),
    "recognize": ("I did not recognize your voice.", "", ""),
    "celebrate": ("We celebrate her birthday today.", "", ""),
    "stupid": ("That was a stupid mistake.", "foolish", "wise"),
    "helpful": ("Your advice was very helpful.", "useful", ""),
    "convenient": ("This app is very convenient.", "", ""),
    "impossible": ("Nothing is impossible.", "", "possible"),
    "medical": ("He needs medical help.", "", ""),
    "outdoor": ("Camping is an outdoor activity.", "", "indoor"),
    "forever": ("I will remember this forever.", "", ""),
    "indeed": ("It was indeed a great show.", "", ""),
    # ---------------- DAY 25
    "wood": ("The table is made of wood.", "", ""),
    "cave": ("Bats sleep in the dark cave.", "", ""),
    "tomb": ("They found an old tomb.", "", ""),
    "tool": ("A hammer is a useful tool.", "", ""),
    "satellite": ("The satellite sends pictures to earth.", "", ""),
    "communication": ("Good communication solves problems.", "", ""),
    "wealth": ("Health is better than wealth.", "", "poverty"),
    "attention": ("Please pay attention to the board.", "", ""),
    "miracle": ("His recovery was a miracle.", "", ""),
    "stream": ("A small stream runs behind our house.", "", ""),
    "wave": ("A big wave hit the boat.", "", ""),
    "value": ("The ring has great value.", "worth", ""),
    "beat": ("Our team will beat theirs.", "", ""),
    "support": ("My family will support my dream.", "", ""),
    "twin": ("My twin looks just like me.", "", ""),
    "chemical": ("This chemical is dangerous.", "", ""),
    "female": ("A female bird built the nest.", "", "male"),
    "fair": ("The judge made a fair decision.", "", "unfair"),
    "respond": ("She did not respond to my call.", "answer", ""),
    "deliver": ("They deliver pizza until midnight.", "", ""),
    "fold": ("Fold the paper in half.", "", ""),
    "include": ("The price will include breakfast.", "", ""),
    "earn": ("He works hard to earn money.", "", "spend"),
    "bet": ("I bet he will win.", "", ""),
    "calm": ("The sea was calm this morning.", "", ""),
    "direct": ("Is there a direct bus to Seoul?", "", ""),
    "thick": ("The book is very thick.", "", "thin"),
    "abstract": ("Abstract art is hard to understand.", "", ""),
    "someday": ("Someday I will travel to Europe.", "", ""),
    "nowadays": ("Nowadays everyone uses a smartphone.", "", ""),
}
