# -*- coding: utf-8 -*-
"""뜯어먹는 1800 DAY 06~15 예문·동의어·반의어. english: (example, synonyms, antonyms)"""
DATA = {
    # ---------------- DAY 06
    "peace": ("We all want world peace.", "", "war"),
    "neighbor": ("My neighbor has a big dog.", "", ""),
    "pet": ("My pet is a small cat.", "", ""),
    "brain": ("The brain needs good rest.", "", ""),
    "age": ("What is your age?", "", ""),
    "subject": ("Math is my hardest subject.", "", ""),
    "fact": ("That story is a true fact.", "truth", ""),
    "price": ("The price is too high.", "cost", ""),
    "custom": ("Every country has its own custom.", "", ""),
    "office": ("My mother works in an office.", "", ""),
    "park": ("We played in the park.", "", ""),
    "rule": ("Please follow the school rule.", "", ""),
    "respect": ("I respect my teacher.", "", ""),
    "check": ("Please check your answers again.", "", ""),
    "bring": ("Bring your book tomorrow.", "", "take"),
    "build": ("They will build a new house.", "", ""),
    "join": ("I want to join the club.", "", ""),
    "lose": ("Do not lose your ticket.", "", "find"),
    "die": ("The flowers will die soon.", "", "live"),
    "half": ("I ate half of the pizza.", "", ""),
    "few": ("Only a few students came.", "", "many"),
    "both": ("Both answers are correct.", "", ""),
    "sick": ("She was sick last week.", "ill", "healthy"),
    "busy": ("My father is very busy today.", "", "free"),
    "real": ("Is this a real diamond?", "", "fake"),
    "wrong": ("Your answer is wrong.", "", "right"),
    "most": ("Most students like music.", "", ""),
    "late": ("I was late for school.", "", "early"),
    "fortunately": ("Fortunately, nobody was hurt.", "", ""),
    "even": ("Even my little sister knows it.", "", ""),
    # ---------------- DAY 07
    "health": ("Good sleep is important for health.", "", ""),
    "holiday": ("Monday is a national holiday.", "", ""),
    "gift": ("I gave her a small gift.", "present", ""),
    "goal": ("My goal is to speak English well.", "", ""),
    "effect": ("Sleep has a good effect on health.", "", ""),
    "field": ("Cows are in the green field.", "", ""),
    "magazine": ("She reads a fashion magazine.", "", ""),
    "sign": ("The sign says stop.", "", ""),
    "report": ("I wrote a book report.", "", ""),
    "order": ("Please put them in order.", "", ""),
    "experience": ("That was a great experience.", "", ""),
    "result": ("The result was very good.", "", ""),
    "ride": ("I ride my bike every day.", "", ""),
    "wish": ("I wish for a white Christmas.", "", ""),
    "human": ("Every human needs water.", "", ""),
    "past": ("Do not worry about the past.", "", "future"),
    "carry": ("Let me carry your bag.", "", ""),
    "draw": ("She can draw very well.", "", ""),
    "spend": ("I spend an hour on homework.", "", "save"),
    "wait": ("Please wait for me here.", "", ""),
    "decide": ("We must decide today.", "", ""),
    "choose": ("You can choose one color.", "pick", ""),
    "true": ("Her story is true.", "", "false"),
    "popular": ("This song is very popular.", "", ""),
    "difficult": ("The test was too difficult.", "hard", "easy"),
    "foreign": ("I want to learn a foreign language.", "", ""),
    "able": ("She is able to swim well.", "", ""),
    "full": ("The box is full of books.", "", "empty"),
    "usually": ("I usually get up at seven.", "", ""),
    "never": ("I never eat breakfast.", "", "always"),
    # ---------------- DAY 08
    "dish": ("Please wash the dish.", "", ""),
    "toy": ("The baby likes this toy.", "", ""),
    "subway": ("I take the subway to school.", "", ""),
    "voice": ("She has a beautiful voice.", "", ""),
    "event": ("The school event starts at noon.", "", ""),
    "opinion": ("May I ask your opinion?", "", ""),
    "solution": ("We found a good solution.", "answer", "problem"),
    "allowance": ("I save my allowance every week.", "", ""),
    "hundred": ("The book has three hundred pages.", "", ""),
    "thousand": ("A thousand people came.", "", ""),
    "century": ("We live in a new century.", "", ""),
    "rest": ("Take a short rest now.", "", ""),
    "waste": ("Do not waste your time.", "", "save"),
    "surprise": ("The gift was a big surprise.", "", ""),
    "bear": ("A brown bear lives in the forest.", "", ""),
    "fight": ("Do not fight with your brother.", "", ""),
    "buy": ("I want to buy a new pen.", "", "sell"),
    "sell": ("They sell fresh bread here.", "", "buy"),
    "follow": ("Please follow me.", "", "lead"),
    "miss": ("Do not miss the last bus.", "", ""),
    "close": ("Please close the door.", "shut", "open"),
    "free": ("The concert is free.", "", ""),
    "upset": ("She was upset about the news.", "", ""),
    "healthy": ("Vegetables are healthy food.", "", "sick"),
    "delicious": ("This soup is delicious.", "tasty", ""),
    "sad": ("The movie made me sad.", "", "happy"),
    "careful": ("Be careful on the stairs.", "", ""),
    "ready": ("Are you ready to go?", "", ""),
    "away": ("The school is far away.", "", ""),
    "however": ("It was cold. However, we went out.", "", ""),
    # ---------------- DAY 09
    "president": ("The president gave a speech.", "", ""),
    "diary": ("I write in my diary every night.", "", ""),
    "cartoon": ("Children love this cartoon.", "", ""),
    "meal": ("Breakfast is my favorite meal.", "", ""),
    "character": ("He has a kind character.", "", ""),
    "reason": ("Please tell me the reason.", "", ""),
    "ground": ("The ball fell on the ground.", "", ""),
    "community": ("Our community is very friendly.", "", ""),
    "glass": ("I drank a glass of milk.", "", ""),
    "weight": ("What is the weight of this box?", "", ""),
    "control": ("You must control your anger.", "", ""),
    "step": ("Take one step forward.", "", ""),
    "matter": ("What is the matter?", "", ""),
    "match": ("We won the soccer match.", "", ""),
    "set": ("Set the box on the table.", "", ""),
    "catch": ("Try to catch the ball.", "", ""),
    "hold": ("Please hold my hand.", "", ""),
    "pick": ("Pick a card, please.", "choose", ""),
    "teach": ("She will teach us English.", "", "learn"),
    "agree": ("I agree with your idea.", "", "disagree"),
    "invent": ("They want to invent a new robot.", "", ""),
    "welcome": ("We welcome new students.", "", ""),
    "bright": ("The sun is very bright.", "", "dark"),
    "smart": ("She is a smart student.", "clever", ""),
    "wise": ("My grandfather is a wise man.", "", ""),
    "hungry": ("I am very hungry now.", "", "full"),
    "fine": ("The weather is fine today.", "", ""),
    "pretty": ("That is a pretty flower.", "", ""),
    "still": ("He is still sleeping.", "", ""),
    "later": ("I will call you later.", "", ""),
    # ---------------- DAY 10
    "teenager[teen]": ("My sister is a teenager.", "", ""),
    "arm": ("He hurt his left arm.", "", ""),
    "skill": ("Cooking is a useful skill.", "", ""),
    "factory": ("My uncle works at a car factory.", "", ""),
    "prize": ("She won first prize.", "", ""),
    "chance": ("This is your last chance.", "", ""),
    "shape": ("The cloud has a funny shape.", "", ""),
    "difference": ("There is a big difference.", "", ""),
    "wall": ("The picture is on the wall.", "", ""),
    "contest": ("I joined a singing contest.", "", ""),
    "race": ("He won the race.", "", ""),
    "smell": ("The flowers smell sweet.", "", ""),
    "interest": ("I have an interest in science.", "", ""),
    "judge": ("Do not judge people by their looks.", "", ""),
    "cause": ("Careless driving can cause accidents.", "", ""),
    "cover": ("Please cover the pot.", "", ""),
    "travel": ("I want to travel around the world.", "", ""),
    "guess": ("Can you guess my age?", "", ""),
    "finish": ("I must finish my homework.", "end", "start"),
    "wash": ("Wash your hands before dinner.", "", ""),
    "introduce": ("Let me introduce my friend.", "", ""),
    "hurt": ("Did you hurt your knee?", "", ""),
    "tired": ("I feel very tired today.", "", ""),
    "proud": ("My parents are proud of me.", "", ""),
    "dirty": ("Your shoes are very dirty.", "", "clean"),
    "angry": ("He was angry at me.", "mad", ""),
    "modern": ("This is a modern building.", "", ""),
    "useful": ("This book is very useful.", "helpful", ""),
    "soon": ("The bus will come soon.", "", ""),
    "once": ("I met him once.", "", ""),
    # ---------------- DAY 11
    "environment": ("We must protect the environment.", "", ""),
    "pollution": ("Air pollution is a big problem.", "", ""),
    "lake": ("We swam in the lake.", "", ""),
    "desert": ("The desert is very hot.", "", ""),
    "insect": ("An ant is a small insect.", "", ""),
    "accident": ("There was a car accident.", "", ""),
    "college": ("My brother goes to college.", "", ""),
    "exam": ("I passed the math exam.", "test", ""),
    "advice": ("Thank you for your advice.", "", ""),
    "hobby": ("My hobby is taking photos.", "", ""),
    "form": ("Please fill in this form.", "", ""),
    "mark": ("Mark the right answer.", "", ""),
    "board": ("The notice is on the board.", "", ""),
    "post": ("I will post the letter today.", "", ""),
    "laugh": ("We laugh at his jokes.", "", "cry"),
    "excuse": ("Excuse me for a moment.", "", ""),
    "pass": ("I hope to pass the exam.", "", "fail"),
    "drive": ("My father will drive us home.", "", ""),
    "receive": ("I receive many emails.", "", "send"),
    "kill": ("Do not kill the insects.", "", ""),
    "climb": ("We will climb the mountain.", "", ""),
    "add": ("Add some salt to the soup.", "", ""),
    "fat": ("The cat is very fat.", "", "thin"),
    "dark": ("The room was too dark.", "", "bright"),
    "whole": ("I ate the whole cake.", "entire", "part"),
    "afraid": ("I am afraid of dogs.", "scared", ""),
    "physical": ("Physical exercise is good for you.", "", ""),
    "dangerous": ("This road is dangerous.", "", "safe"),
    "off": ("Please turn off the light.", "", ""),
    "ever": ("Have you ever been to Japan?", "", ""),
    # ---------------- DAY 12
    "clerk": ("The clerk was very kind.", "", ""),
    "riddle": ("Can you solve this riddle?", "", ""),
    "company": ("He works for a big company.", "", ""),
    "garage": ("The car is in the garage.", "", ""),
    "palace": ("The king lives in a palace.", "", ""),
    "hole": ("There is a hole in my sock.", "", ""),
    "bill": ("Please pay the bill.", "", ""),
    "seed": ("Plant the seed in the soil.", "", ""),
    "medicine": ("Take this medicine after meals.", "", ""),
    "luck": ("Good luck on your test.", "", ""),
    "meaning": ("What is the meaning of this word?", "", ""),
    "volunteer": ("She works as a volunteer.", "", ""),
    "view": ("The room has a great view.", "", ""),
    "lie": ("Do not tell a lie.", "", "truth"),
    "act": ("We must act right now.", "", ""),
    "pay": ("I will pay for lunch.", "", ""),
    "shout": ("Do not shout in the library.", "", ""),
    "cross": ("Cross the street carefully.", "", ""),
    "seem": ("You seem very tired.", "", ""),
    "invite": ("I will invite my friends.", "", ""),
    "arrive": ("We arrive at nine.", "", "leave"),
    "collect": ("I collect old coins.", "gather", ""),
    "rich": ("He is a rich man.", "", "poor"),
    "blind": ("The blind man walks with a dog.", "", ""),
    "heavy": ("This box is too heavy.", "", "light"),
    "terrible": ("The weather was terrible.", "", ""),
    "strange": ("That was a strange dream.", "", ""),
    "possible": ("Is it possible to finish today?", "", "impossible"),
    "maybe": ("Maybe he will come later.", "perhaps", ""),
    "ago": ("I met her two years ago.", "", ""),
    # ---------------- DAY 13
    "sense": ("Dogs have a good sense of smell.", "", ""),
    "pleasure": ("It is a pleasure to meet you.", "", ""),
    "image": ("The image is very clear.", "", ""),
    "map": ("Look at the world map.", "", ""),
    "project": ("We finished the science project.", "", ""),
    "traffic": ("The traffic was very heavy.", "", ""),
    "safety": ("Safety comes first.", "", ""),
    "spaceship": ("The spaceship left the earth.", "", ""),
    "rainbow": ("A rainbow appeared after the rain.", "", ""),
    "million": ("The city has one million people.", "", ""),
    "model": ("He made a model of a ship.", "", ""),
    "type": ("What type of music do you like?", "", ""),
    "block": ("Do not block the door.", "", ""),
    "seat": ("This seat is empty.", "", ""),
    "touch": ("Do not touch the painting.", "", ""),
    "wonder": ("I wonder where she is.", "", ""),
    "magic": ("The magic show was fun.", "", ""),
    "secret": ("Can you keep a secret?", "", ""),
    "general": ("This is a general rule.", "", ""),
    "prepare": ("We prepare dinner together.", "", ""),
    "imagine": ("Imagine a world without water.", "", ""),
    "forget": ("Do not forget your umbrella.", "", "remember"),
    "develop": ("Children develop very fast.", "", ""),
    "recycle": ("We recycle paper and cans.", "", ""),
    "several": ("I read several books.", "", ""),
    "funny": ("His story was very funny.", "", ""),
    "safe": ("This place is safe at night.", "", "dangerous"),
    "enough": ("We have enough time.", "", ""),
    "loud": ("The music is too loud.", "", "quiet"),
    "far": ("The station is not far.", "", "near"),
    # ---------------- DAY 14
    "truth": ("Please tell me the truth.", "", "lie"),
    "success": ("Hard work brings success.", "", "failure"),
    "friendship": ("Our friendship is very strong.", "", ""),
    "being": ("A human being needs love.", "", ""),
    "goods": ("The store sells many goods.", "", ""),
    "coin": ("I found a gold coin.", "", ""),
    "bank": ("The bank opens at nine.", "", ""),
    "address": ("Write your address here.", "", ""),
    "electricity": ("We should save electricity.", "", ""),
    "law": ("Everyone must follow the law.", "", ""),
    "campaign": ("They started a clean-up campaign.", "", ""),
    "sentence": ("Read the first sentence.", "", ""),
    "heat": ("The heat was terrible yesterday.", "", ""),
    "circle": ("Draw a big circle.", "", ""),
    "reach": ("We will reach the top soon.", "", ""),
    "mix": ("Mix the eggs and milk.", "blend", ""),
    "excite": ("Fast games excite young children.", "", ""),
    "rise": ("The sun will rise soon.", "", "fall"),
    "lead": ("She will lead our team.", "guide", "follow"),
    "enter": ("Please do not enter this room.", "", ""),
    "fill": ("Fill the glass with water.", "", "empty"),
    "produce": ("They produce fresh milk here.", "make", ""),
    "cool": ("The wind is cool today.", "", "warm"),
    "slow": ("The bus was very slow.", "", "fast"),
    "clear": ("Your voice is very clear.", "", ""),
    "false": ("That answer is false.", "", "true"),
    "national": ("The national flag is beautiful.", "", ""),
    "main": ("What is the main idea?", "", ""),
    "almost": ("It is almost eight o'clock.", "nearly", ""),
    "finally": ("We finally arrived home.", "", ""),
    # ---------------- DAY 15
    "library": ("I borrowed books from the library.", "", ""),
    "museum": ("We visited a science museum.", "", ""),
    "ocean": ("The ocean is very deep.", "sea", ""),
    "bone": ("The dog is eating a bone.", "", ""),
    "bath": ("I take a bath every night.", "", ""),
    "pity": ("What a pity!", "", ""),
    "proverb": ("This proverb teaches patience.", "", ""),
    "product": ("This product is very popular.", "", ""),
    "invention": ("The wheel was a great invention.", "", ""),
    "technology": ("Technology changes our life.", "", ""),
    "trash": ("Please throw the trash away.", "garbage", ""),
    "moment": ("Wait a moment, please.", "", ""),
    "date": ("What is the date today?", "", ""),
    "taste": ("This cake has a sweet taste.", "", ""),
    "balance": ("Keep your balance on the bike.", "", ""),
    "ring": ("She wears a gold ring.", "", ""),
    "share": ("Let us share the pizza.", "", ""),
    "return": ("We return home at six.", "", ""),
    "lift": ("Can you lift this box?", "raise", ""),
    "raise": ("Please raise your hand.", "lift", ""),
    "explain": ("Can you explain this rule?", "", ""),
    "marry": ("They will marry next spring.", "", ""),
    "exciting": ("The game was very exciting.", "", "boring"),
    "common": ("This is a common mistake.", "", "rare"),
    "global": ("Global warming is serious.", "", ""),
    "regular": ("Regular exercise keeps you healthy.", "", ""),
    "serious": ("This is a serious problem.", "", ""),
    "fresh": ("I bought fresh fruit.", "", ""),
    "probably": ("He will probably come late.", "", ""),
    "else": ("Do you need anything else?", "", ""),
}
