# -*- coding: utf-8 -*-
"""뜯어먹는 1800 DAY 26~35 예문·동의어·반의어. english: (example, synonyms, antonyms)"""
DATA = {
    # ---------------- DAY 26
    "lawyer": ("My aunt works as a lawyer.", "", ""),
    "officer": ("A police officer stopped the car.", "", ""),
    "university": ("She studies at a university.", "college", ""),
    "level": ("The water level is rising.", "", ""),
    "growth": ("The growth of the city is fast.", "", ""),
    "journey": ("Our journey took three days.", "trip", ""),
    "gun": ("The soldier carried a gun.", "", ""),
    "emergency": ("Call this number in an emergency.", "", ""),
    "case": ("In that case, we should wait.", "", ""),
    "difficulty": ("I had difficulty finding your house.", "", ""),
    "addition": ("We learned addition in math class.", "", ""),
    "credit": ("She paid with a credit card.", "", ""),
    "fool": ("Do not fool your friends.", "", ""),
    "harvest": ("Farmers harvest rice in autumn.", "", ""),
    "figure": ("The figure shows last year's sales.", "", ""),
    "tie": ("Please tie your shoelaces.", "", ""),
    "boil": ("Boil the water for five minutes.", "", ""),
    "borrow": ("May I borrow your pen?", "", "lend"),
    "belong": ("These books belong to the library.", "", ""),
    "communicate": ("We communicate by email.", "", ""),
    "confuse": ("These two words often confuse me.", "", ""),
    "survive": ("Few plants survive in the desert.", "", ""),
    "handsome": ("He is a handsome young man.", "", ""),
    "gentle": ("She has a gentle voice.", "", ""),
    "mad": ("My mother was mad at me.", "angry", ""),
    "merry": ("We had a merry time together.", "", ""),
    "noisy": ("The classroom was too noisy.", "", "quiet"),
    "scientific": ("They did a scientific study.", "", ""),
    "mostly": ("The students are mostly boys.", "", ""),
    "anywhere": ("I cannot find my key anywhere.", "", ""),
    # ---------------- DAY 27
    "captain": ("The captain led the ship safely.", "", ""),
    "stranger": ("Do not follow a stranger.", "", ""),
    "statue": ("A stone statue stands in the park.", "", ""),
    "spirit": ("The team showed a fighting spirit.", "", ""),
    "scenery": ("The mountain scenery is beautiful.", "", ""),
    "gesture": ("He made a friendly gesture.", "", ""),
    "pole": ("The flag hangs on a tall pole.", "", ""),
    "rubber": ("These gloves are made of rubber.", "", ""),
    "structure": ("The structure of the bridge is strong.", "", ""),
    "root": ("The root of the tree is deep.", "", ""),
    "schedule": ("Check the bus schedule first.", "", ""),
    "tour": ("We joined a city tour.", "", ""),
    "charge": ("There is no charge for children.", "", ""),
    "decrease": ("Prices will decrease next month.", "", "increase"),
    "review": ("I review my notes every night.", "", ""),
    "vote": ("Adults vote for their leaders.", "", ""),
    "attend": ("All students must attend the meeting.", "", ""),
    "discuss": ("Let us discuss the plan.", "", ""),
    "settle": ("They settle every problem calmly.", "", ""),
    "elect": ("We elect a class president each year.", "", ""),
    "achieve": ("You can achieve your goal.", "", ""),
    "appreciate": ("I appreciate your kind help.", "", ""),
    "brave": ("The brave boy saved the cat.", "", ""),
    "cheap": ("This shirt was very cheap.", "", "expensive"),
    "classical": ("My father enjoys classical music.", "", ""),
    "familiar": ("Her face looks familiar.", "", "strange"),
    "unknown": ("The singer was unknown last year.", "", "famous"),
    "uncomfortable": ("This chair is uncomfortable.", "", "comfortable"),
    "simply": ("Just answer simply yes or no.", "", ""),
    "anyway": ("It was raining, but we went anyway.", "", ""),
    # ---------------- DAY 28
    "population": ("The population of Seoul is large.", "", ""),
    "coast": ("We drove along the coast.", "", ""),
    "bucket": ("Fill the bucket with water.", "", ""),
    "cart": ("She pushed the shopping cart.", "", ""),
    "cage": ("The bird flew out of the cage.", "", ""),
    "screen": ("The screen is too bright.", "", ""),
    "kite": ("We flew a kite in the park.", "", ""),
    "autumn": ("Leaves turn red in autumn.", "fall", ""),
    "breeze": ("A cool breeze came from the sea.", "", ""),
    "mess": ("Your room is a total mess.", "", ""),
    "litter": ("Do not drop litter on the street.", "trash", ""),
    "joke": ("His joke made everyone laugh.", "", ""),
    "hike": ("We hike in the mountains every spring.", "", ""),
    "fear": ("She has a fear of high places.", "", ""),
    "offer": ("They will offer free lessons.", "", ""),
    "remain": ("Please remain in your seat.", "stay", ""),
    "repair": ("He can repair old clocks.", "fix", ""),
    "blank": ("Fill in the blank with a verb.", "", ""),
    "final": ("This is the final question.", "last", "first"),
    "public": ("The park is open to the public.", "", "private"),
    "bend": ("Bend your knees slowly.", "", ""),
    "float": ("Wood will float on water.", "", "sink"),
    "bark": ("Dogs bark at strangers.", "", ""),
    "concentrate": ("I cannot concentrate in a noisy room.", "", ""),
    "dead": ("The old tree is dead.", "", "alive"),
    "personal": ("This is my personal diary.", "", ""),
    "historic": ("Gyeongju is a historic city.", "", ""),
    "western": ("She likes western movies.", "", "eastern"),
    "ahead": ("The station is straight ahead.", "", ""),
    "exactly": ("Tell me exactly what happened.", "", ""),
    # ---------------- DAY 29
    "government": ("The government built a new road.", "", ""),
    "stomach": ("My stomach hurts after lunch.", "", ""),
    "flour": ("Bread is made from flour.", "", ""),
    "doll": ("The girl hugged her doll.", "", ""),
    "cyberspace": ("We meet friends in cyberspace.", "", ""),
    "strength": ("He has the strength to lift it.", "power", "weakness"),
    "will": ("She has a strong will to win.", "", ""),
    "development": ("The development of the app took a year.", "", ""),
    "engineering": ("My brother studies engineering.", "", ""),
    "edge": ("Do not stand near the edge.", "", ""),
    "pattern": ("The shirt has a flower pattern.", "", ""),
    "alarm": ("My alarm rings at six.", "", ""),
    "dot": ("Put a dot at the end.", "", ""),
    "cost": ("The trip will cost too much.", "price", ""),
    "focus": ("Please focus on your work.", "", ""),
    "shock": ("The news gave us a shock.", "", ""),
    "reward": ("He got a reward for his honesty.", "", ""),
    "impress": ("Her speech did impress the judges.", "", ""),
    "replace": ("We must replace the old lamp.", "", ""),
    "fail": ("Do not fail the final exam.", "", "succeed"),
    "skip": ("Never skip your breakfast.", "", ""),
    "necessary": ("Sleep is necessary for children.", "", ""),
    "elementary": ("My cousin is in elementary school.", "", ""),
    "fantastic": ("The concert was fantastic.", "", ""),
    "tasty": ("This bread is very tasty.", "delicious", ""),
    "flat": ("The land here is flat.", "", ""),
    "tough": ("The job was really tough.", "hard", ""),
    "crowded": ("The bus was very crowded.", "", "empty"),
    "forward": ("Please step forward.", "", "backward"),
    "badly": ("He was badly hurt in the accident.", "", ""),
    # ---------------- DAY 30
    "climate": ("The climate here is warm.", "", ""),
    "degree": ("The temperature fell one degree.", "", ""),
    "article": ("I read an article about space.", "", ""),
    "metal": ("This box is made of metal.", "", ""),
    "monster": ("The child drew a green monster.", "", ""),
    "treasure": ("They found buried treasure.", "", ""),
    "symbol": ("A dove is a symbol of peace.", "", ""),
    "ceremony": ("The opening ceremony starts at ten.", "", ""),
    "congratulation": ("Please accept my congratulation.", "", ""),
    "breath": ("Take a deep breath now.", "", ""),
    "death": ("His death made us all sad.", "", "birth"),
    "headache": ("I have a bad headache.", "", ""),
    "muscle": ("Exercise makes your muscle strong.", "", ""),
    "base": ("The base of the lamp is heavy.", "", ""),
    "lock": ("Please lock the door at night.", "", ""),
    "dislike": ("I dislike cold weather.", "hate", "like"),
    "feed": ("I feed my dog twice a day.", "", ""),
    "lend": ("Can you lend me your book?", "", "borrow"),
    "suffer": ("Many people suffer from headaches.", "", ""),
    "hang": ("Hang your coat on the hook.", "", ""),
    "wrap": ("Please wrap the gift nicely.", "", ""),
    "pleasant": ("We had a pleasant afternoon.", "", ""),
    "lonely": ("He felt lonely in the big city.", "", ""),
    "thirsty": ("I am thirsty after running.", "", ""),
    "polite": ("She is polite to everybody.", "", "rude"),
    "rude": ("That answer was very rude.", "", "polite"),
    "excellent": ("Your report is excellent.", "", ""),
    "overweight": ("The dog is a little overweight.", "", ""),
    "perhaps": ("Perhaps it will snow tonight.", "maybe", ""),
    "twice": ("I brush my teeth twice a day.", "", ""),
    # ---------------- DAY 31
    "heaven": ("They believe in heaven.", "", ""),
    "myth": ("This is an old Greek myth.", "", ""),
    "sand": ("The children played in the sand.", "", ""),
    "castle": ("An old castle stands on the hill.", "", ""),
    "kindness": ("Thank you for your kindness.", "", ""),
    "concentration": ("Studying needs deep concentration.", "", ""),
    "mystery": ("His sudden trip is a mystery.", "", ""),
    "battle": ("The battle lasted three days.", "", ""),
    "industry": ("The car industry is growing.", "", ""),
    "pile": ("A pile of books is on the desk.", "", ""),
    "chat": ("We had a short chat after class.", "", ""),
    "puzzle": ("This puzzle is hard to solve.", "", ""),
    "text": ("Send me a text when you arrive.", "", ""),
    "advance": ("Science makes rapid advance.", "", ""),
    "graduate": ("I will graduate next year.", "", ""),
    "predict": ("Nobody can predict the future.", "", ""),
    "compare": ("Compare these two pictures.", "", ""),
    "complain": ("He did not complain about the food.", "", ""),
    "forgive": ("Please forgive my mistake.", "", ""),
    "determine": ("Hard work will determine your future.", "", ""),
    "exist": ("Dinosaurs no longer exist.", "", ""),
    "dive": ("He can dive into deep water.", "", ""),
    "upper": ("My room is on the upper floor.", "", "lower"),
    "central": ("We met at the central station.", "", ""),
    "normal": ("His temperature is normal.", "", ""),
    "similar": ("Our bags look similar.", "alike", "different"),
    "honest": ("She is an honest girl.", "", ""),
    "ashamed": ("He felt ashamed of his lie.", "", ""),
    "anymore": ("I do not play games anymore.", "", ""),
    "besides": ("Besides English, she speaks French.", "", ""),
    # ---------------- DAY 32
    "generation": ("My generation grew up with computers.", "", ""),
    "self": ("Believe in your true self.", "", ""),
    "visitor": ("A visitor is waiting outside.", "guest", ""),
    "boss": ("My boss is very kind.", "", ""),
    "portrait": ("She painted a portrait of her father.", "", ""),
    "darkness": ("The cat disappeared into the darkness.", "", "light"),
    "earthquake": ("The earthquake shook the whole town.", "", ""),
    "weapon": ("A sword is an old weapon.", "", ""),
    "charity": ("They gave money to charity.", "", ""),
    "saying": ("There is an old saying about time.", "proverb", ""),
    "issue": ("Pollution is a serious issue.", "", ""),
    "signal": ("The green signal means go.", "", ""),
    "exchange": ("We exchange gifts at Christmas.", "", ""),
    "swallow": ("Chew well before you swallow.", "", ""),
    "average": ("His score is above average.", "", ""),
    "official": ("This is the official result.", "", ""),
    "gray": ("The sky turned gray.", "", ""),
    "prefer": ("I prefer tea to coffee.", "", ""),
    "relax": ("Sit down and relax for a while.", "rest", ""),
    "reduce": ("We must reduce plastic waste.", "decrease", "increase"),
    "bury": ("Dogs bury bones in the yard.", "", ""),
    "shoot": ("Do not shoot at the birds.", "", ""),
    "yell": ("Please do not yell at me.", "shout", ""),
    "powerful": ("The engine is very powerful.", "strong", "weak"),
    "faithful": ("A dog is a faithful friend.", "", ""),
    "creative": ("She has a creative mind.", "", ""),
    "deaf": ("The deaf boy reads lips well.", "", ""),
    "electronic": ("We use electronic dictionaries.", "", ""),
    "nearly": ("It is nearly midnight.", "almost", ""),
    "happily": ("They lived happily together.", "", ""),
    # ---------------- DAY 33
    "ancestor": ("Our ancestor built this house.", "", ""),
    "director": ("The director gave the actors advice.", "", ""),
    "customer": ("The customer asked for a refund.", "", ""),
    "astronaut": ("The astronaut walked on the moon.", "", ""),
    "dynasty": ("The Joseon dynasty lasted long.", "", ""),
    "furniture": ("We bought new furniture.", "", ""),
    "drug": ("Take this drug after meals.", "medicine", ""),
    "greenhouse": ("Tomatoes grow in the greenhouse.", "", ""),
    "harmony": ("The colors are in harmony.", "", ""),
    "dirt": ("Wash the dirt off your hands.", "", ""),
    "shot": ("His last shot won the game.", "", ""),
    "curve": ("Slow down at the curve.", "", ""),
    "stuff": ("Put your stuff in the box.", "", ""),
    "pack": ("Pack your bag before bedtime.", "", ""),
    "spill": ("Do not spill the milk.", "", ""),
    "debate": ("We had a debate about school rules.", "", ""),
    "whisper": ("Please whisper in the library.", "", "shout"),
    "lay": ("Lay the baby on the bed.", "", ""),
    "pardon": ("Pardon me for being late.", "forgive", ""),
    "beg": ("I beg you to listen.", "", ""),
    "relate": ("These two stories relate to each other.", "", ""),
    "intelligent": ("Dolphins are intelligent animals.", "smart", ""),
    "eager": ("She is eager to learn Chinese.", "", ""),
    "disabled": ("This seat is for disabled people.", "", ""),
    "homeless": ("They helped homeless families.", "", ""),
    "harmful": ("Smoking is harmful to health.", "", "helpful"),
    "lifelong": ("Reading is my lifelong hobby.", "", ""),
    "nervous": ("I feel nervous before a test.", "", "calm"),
    "seldom": ("He seldom watches television.", "", "often"),
    "somewhere": ("I left my hat somewhere.", "", ""),
    # ---------------- DAY 34
    "birth": ("The birth of her baby was joyful.", "", "death"),
    "childhood": ("I had a happy childhood.", "", ""),
    "education": ("Education opens many doors.", "", ""),
    "emotion": ("Music can change your emotion.", "feeling", ""),
    "attitude": ("His attitude toward work is good.", "", ""),
    "courage": ("It takes courage to say sorry.", "bravery", ""),
    "condition": ("The car is in good condition.", "", ""),
    "fever": ("The child has a high fever.", "", ""),
    "conversation": ("We had a long conversation.", "talk", ""),
    "adventure": ("The trip was a great adventure.", "", ""),
    "triangle": ("Draw a triangle on the paper.", "", ""),
    "bulb": ("The bulb in my lamp burned out.", "", ""),
    "attack": ("Wild dogs may attack sheep.", "", "defend"),
    "cough": ("He began to cough loudly.", "", ""),
    "flow": ("Rivers flow into the sea.", "", ""),
    "search": ("They search for the lost boy.", "", ""),
    "original": ("This is the original painting.", "", "copy"),
    "opposite": ("The bank is on the opposite side.", "", ""),
    "jog": ("I jog in the park every morning.", "", ""),
    "scan": ("Scan the page for key words.", "", ""),
    "describe": ("Can you describe the man?", "", ""),
    "freeze": ("Water will freeze at zero.", "", "melt"),
    "remove": ("Please remove your shoes here.", "", ""),
    "single": ("Not a single student was late.", "", ""),
    "positive": ("Keep a positive attitude.", "", "negative"),
    "ugly": ("The old building looks ugly.", "", "beautiful"),
    "northern": ("Winters are cold in northern areas.", "", "southern"),
    "nearby": ("A nearby shop sells fresh bread.", "", ""),
    "upside down": ("The picture is upside down.", "", ""),
    "downtown": ("We shopped downtown yesterday.", "", ""),
    # ---------------- DAY 35
    "thief": ("The thief ran into the alley.", "", ""),
    "lifetime": ("This chance comes once in a lifetime.", "", ""),
    "career": ("She started her career as a nurse.", "", ""),
    "economy": ("The economy is growing slowly.", "", ""),
    "fur": ("The rabbit has soft fur.", "", ""),
    "engine": ("The engine makes a strange noise.", "", ""),
    "poetry": ("I enjoy reading poetry.", "", ""),
    "border": ("They crossed the border at dawn.", "", ""),
    "disaster": ("The flood was a terrible disaster.", "", ""),
    "filter": ("Change the water filter monthly.", "", ""),
    "forecast": ("The forecast says it will rain.", "", ""),
    "quarrel": ("They had a small quarrel.", "fight", ""),
    "harm": ("Too much sugar can harm you.", "hurt", ""),
    "regard": ("Please give my regard to your mother.", "", ""),
    "sneeze": ("Cover your mouth when you sneeze.", "", ""),
    "sink": ("Heavy stones sink in water.", "", "float"),
    "characteristic": ("Kindness is her main characteristic.", "", ""),
    "professional": ("He is a professional cook.", "", ""),
    "encourage": ("My teacher will encourage me.", "cheer", ""),
    "reflect": ("The lake will reflect the moonlight.", "", ""),
    "slide": ("Children slide down the hill.", "", ""),
    "stretch": ("Stretch your arms before running.", "", ""),
    "steal": ("Never steal other people's things.", "", ""),
    "comic": ("He told a comic story.", "funny", ""),
    "anxious": ("She is anxious about the result.", "worried", ""),
    "asleep": ("The baby is already asleep.", "", "awake"),
    "effective": ("This medicine is very effective.", "", ""),
    "due": ("The report is due on Friday.", "", ""),
    "actually": ("Actually, I have never been there.", "", ""),
    "rather": ("The soup is rather salty.", "", ""),
}
