# -*- coding: utf-8 -*-
"""뜯어먹는 1800 DAY 46~60 예문·동의어·반의어. english: (example, synonyms, antonyms)"""
DATA = {
    # ---------------- DAY 46
    "passenger": ("Every passenger must wear a seat belt.", "", ""),
    "continent": ("Africa is a large continent.", "", ""),
    "port": ("The ship reached the port at dawn.", "harbor", ""),
    "cooperation": ("Your cooperation made this possible.", "", ""),
    "competition": ("She won the singing competition.", "contest", ""),
    "convenience": ("This app was made for convenience.", "", ""),
    "curiosity": ("Curiosity led him to the cave.", "", ""),
    "suicide": ("The film deals with suicide.", "", ""),
    "bullet": ("A bullet went through the wall.", "", ""),
    "descendant": ("He is a descendant of a king.", "", "ancestor"),
    "collection": ("His coin collection is famous.", "", ""),
    "desire": ("She has a strong desire to learn.", "wish", ""),
    "export": ("They export cars to Europe.", "", "import"),
    "blend": ("Blend the milk and eggs well.", "mix", ""),
    "stare": ("Do not stare at strangers.", "", ""),
    "deceive": ("He tried to deceive his teacher.", "cheat", ""),
    "commit": ("Nobody should commit a crime.", "", ""),
    "twist": ("Twist the cap to open it.", "", ""),
    "decorate": ("We decorate the tree in December.", "", ""),
    "tend": ("Children tend to copy adults.", "", ""),
    "firm": ("She works for a law firm.", "", ""),
    "senior": ("My senior helped me a lot.", "", "junior"),
    "major": ("This is a major problem.", "main", "minor"),
    "minor": ("It was only a minor injury.", "small", "major"),
    "individual": ("Each individual has a duty.", "", ""),
    "current": ("The current price is too high.", "present", ""),
    "grand": ("They stayed in a grand hotel.", "", ""),
    "odd": ("An odd noise came from upstairs.", "strange", ""),
    "awkward": ("There was an awkward silence.", "", ""),
    "directly": ("Go directly to the station.", "", ""),
    # ---------------- DAY 47
    "novel": ("She wrote her first novel at twenty.", "", ""),
    "grave": ("Flowers lay on the grave.", "tomb", ""),
    "crime": ("Stealing is a serious crime.", "", ""),
    "prison": ("The thief was sent to prison.", "jail", ""),
    "blanket": ("Cover the baby with a blanket.", "", ""),
    "skin": ("Sunlight can damage your skin.", "", ""),
    "instance": ("Give me one clear instance.", "example", ""),
    "element": ("Water is an important element of life.", "", ""),
    "dozen": ("She bought a dozen eggs.", "", ""),
    "honesty": ("His honesty impressed everyone.", "", ""),
    "duty": ("It is your duty to help.", "", ""),
    "failure": ("Failure teaches useful lessons.", "", "success"),
    "rate": ("The birth rate is falling.", "", ""),
    "progress": ("She made great progress in math.", "", ""),
    "trade": ("The two nations trade freely.", "", ""),
    "doubt": ("I doubt his story.", "", ""),
    "march": ("The soldiers march every morning.", "", ""),
    "delay": ("Snow will delay the train.", "", ""),
    "satisfy": ("This answer did not satisfy me.", "", ""),
    "misunderstand": ("Please do not misunderstand my words.", "", ""),
    "scold": ("Mom will scold me for this.", "", "praise"),
    "apply": ("I will apply for the summer camp.", "", ""),
    "drown": ("Never swim alone; you may drown.", "", ""),
    "broad": ("The river is very broad here.", "wide", "narrow"),
    "cruel": ("Do not be cruel to animals.", "", "kind"),
    "private": ("This is a private letter.", "", "public"),
    "urgent": ("I have an urgent message.", "", ""),
    "military": ("He joined the military service.", "", ""),
    "historical": ("This is a historical novel.", "", ""),
    "fully": ("The room was fully booked.", "completely", ""),
    # ---------------- DAY 48
    "universe": ("The universe is still growing.", "", ""),
    "laughter": ("Laughter filled the classroom.", "", ""),
    "knee": ("He fell and hurt his knee.", "", ""),
    "gym": ("We play basketball in the gym.", "", ""),
    "equipment": ("The camping equipment is heavy.", "", ""),
    "rope": ("Pull the rope with both hands.", "", ""),
    "refrigerator": ("Put the milk in the refrigerator.", "", ""),
    "production": ("Car production increased last year.", "", ""),
    "tradition": ("Eating rice cake is a tradition.", "custom", ""),
    "religion": ("People of every religion came.", "", ""),
    "semester": ("The new semester begins in March.", "term", ""),
    "shadow": ("My shadow grew long at sunset.", "", ""),
    "flea": ("The dog has a flea problem.", "", ""),
    "plug": ("Pull out the plug after use.", "", ""),
    "ache": ("My legs ache after the hike.", "hurt", ""),
    "handle": ("She can handle any problem.", "", ""),
    "pause": ("Let us pause for five minutes.", "stop", ""),
    "admire": ("I admire her courage.", "respect", ""),
    "apologize": ("You should apologize to him.", "", ""),
    "threaten": ("Pollution will threaten our health.", "", ""),
    "arrest": ("The police will arrest the thief.", "", ""),
    "select": ("Select one answer only.", "choose", ""),
    "narrow": ("The path is too narrow.", "", "wide"),
    "attractive": ("She has an attractive smile.", "", ""),
    "awful": ("The weather was awful yesterday.", "terrible", ""),
    "casual": ("Wear casual clothes to the picnic.", "", "formal"),
    "capable": ("She is capable of great work.", "able", ""),
    "absent": ("Two students were absent today.", "", "present"),
    "alike": ("The twins look very alike.", "similar", ""),
    "otherwise": ("Hurry, otherwise we will be late.", "", ""),
    # ---------------- DAY 49
    "citizen": ("Every citizen has the right to vote.", "", ""),
    "fare": ("The bus fare went up.", "", ""),
    "tale": ("Grandmother told us an old tale.", "story", ""),
    "suggestion": ("Your suggestion sounds good.", "", ""),
    "responsibility": ("Caring for a pet is a responsibility.", "duty", ""),
    "risk": ("Driving fast is a big risk.", "danger", ""),
    "intelligence": ("Dolphins show high intelligence.", "", ""),
    "viewpoint": ("From my viewpoint, the plan is fine.", "", ""),
    "shell": ("The turtle hid inside its shell.", "", ""),
    "surface": ("The surface of the desk is smooth.", "", ""),
    "version": ("This is the new version of the app.", "", ""),
    "account": ("She opened a bank account.", "", ""),
    "influence": ("Friends influence our choices.", "affect", ""),
    "hesitate": ("Do not hesitate to ask me.", "", ""),
    "fasten": ("Please fasten your seat belt.", "tie", ""),
    "manufacture": ("They manufacture shoes here.", "produce", ""),
    "hire": ("The shop will hire two students.", "employ", "fire"),
    "examine": ("The doctor will examine your eyes.", "check", ""),
    "explode": ("The balloon may explode.", "", ""),
    "erase": ("Erase the board before class.", "", ""),
    "interrupt": ("Do not interrupt the speaker.", "", ""),
    "deny": ("He did not deny the truth.", "", "admit"),
    "former": ("Our former teacher visited us.", "", ""),
    "clever": ("That was a clever idea.", "smart", ""),
    "distant": ("They live in a distant village.", "far", "near"),
    "faint": ("I heard a faint sound.", "", ""),
    "double": ("Ask for a double portion.", "", ""),
    "entire": ("The entire class agreed.", "whole", ""),
    "frequent": ("He is a frequent visitor here.", "", ""),
    "possibly": ("She could possibly arrive late.", "maybe", ""),
    # ---------------- DAY 50
    "author": ("The author signed my book.", "writer", ""),
    "secretary": ("The secretary answered the phone.", "", ""),
    "beggar": ("A beggar sat by the gate.", "", ""),
    "shepherd": ("The shepherd led the sheep home.", "", ""),
    "fable": ("This fable teaches honesty.", "", ""),
    "tongue": ("Do not burn your tongue.", "", ""),
    "departure": ("Our departure was delayed.", "", "arrival"),
    "entrance": ("Wait at the main entrance.", "", "exit"),
    "method": ("This method saves time.", "way", ""),
    "aptitude": ("She has an aptitude for languages.", "talent", ""),
    "victory": ("The team celebrated its victory.", "", "defeat"),
    "chain": ("The dog broke its chain.", "", ""),
    "billion": ("The company earned one billion dollars.", "", ""),
    "blossom": ("Cherry blossom covers the hill.", "", ""),
    "praise": ("The teacher gave him praise.", "", "scold"),
    "wind": ("Please wind the clock.", "", ""),
    "require": ("Plants require light and water.", "need", ""),
    "tremble": ("My hands tremble in the cold.", "shake", ""),
    "starve": ("Nobody should starve in our town.", "", ""),
    "quit": ("He decided to quit smoking.", "stop", ""),
    "spoil": ("Rain will spoil our plan.", "ruin", ""),
    "punish": ("Do not punish the child harshly.", "", ""),
    "translate": ("Can you translate this letter?", "", ""),
    "wealthy": ("The wealthy man gave to charity.", "rich", "poor"),
    "independent": ("She is an independent thinker.", "", ""),
    "mild": ("The winter was quite mild.", "", "harsh"),
    "harsh": ("The desert has a harsh climate.", "", "mild"),
    "informal": ("It was an informal meeting.", "casual", "formal"),
    "lunar": ("We celebrate the lunar new year.", "", ""),
    "overseas": ("My cousin studies overseas.", "abroad", ""),
    # ---------------- DAY 51
    "client": ("The lawyer met his client.", "customer", ""),
    "clown": ("The clown made the children laugh.", "", ""),
    "empire": ("The empire ruled many lands.", "", ""),
    "dragon": ("A dragon appears in this tale.", "", ""),
    "nail": ("She painted her nail red.", "", ""),
    "baggage": ("Our baggage arrived late.", "luggage", ""),
    "label": ("Read the label before you buy.", "", ""),
    "coal": ("They burned coal for heat.", "", ""),
    "bubble": ("A soap bubble floated away.", "", ""),
    "bug": ("A small bug crawled on the leaf.", "insect", ""),
    "dawn": ("We left home at dawn.", "", "dusk"),
    "detail": ("Explain every detail, please.", "", ""),
    "plenty": ("We have plenty of time.", "", ""),
    "delight": ("Her gift gave me great delight.", "joy", ""),
    "dispute": ("The two nations had a long dispute.", "conflict", ""),
    "flame": ("The flame of the candle danced.", "", ""),
    "flash": ("A flash of light woke me.", "", ""),
    "regret": ("I regret my rude words.", "", ""),
    "bless": ("May God bless your family.", "", ""),
    "spell": ("Can you spell your last name?", "", ""),
    "surround": ("Tall trees surround the house.", "", ""),
    "swear": ("I swear to tell the truth.", "promise", ""),
    "wander": ("We wander around the old town.", "", ""),
    "generous": ("He is generous to everyone.", "", "selfish"),
    "thankful": ("I am thankful for your help.", "grateful", ""),
    "instant": ("She gave an instant answer.", "immediate", ""),
    "medium": ("I wear a medium size.", "", ""),
    "virtual": ("We took a virtual tour.", "", ""),
    "illegal": ("Parking here is illegal.", "", "legal"),
    "either": ("I do not like it either.", "", ""),
    # ---------------- DAY 52
    "counselor": ("The school counselor listened to me.", "", ""),
    "opportunity": ("This is a great opportunity.", "chance", ""),
    "literature": ("She studies English literature.", "", ""),
    "illusion": ("The picture creates an illusion.", "", ""),
    "leisure": ("I read books in my leisure time.", "", ""),
    "shuttle": ("A shuttle runs to the airport.", "", ""),
    "location": ("The shop has a good location.", "place", ""),
    "laundry": ("I do the laundry on Sunday.", "", ""),
    "witch": ("The witch appears in many tales.", "", ""),
    "length": ("Measure the length of the rope.", "", ""),
    "relation": ("There is no relation between them.", "", ""),
    "popularity": ("The song gained popularity fast.", "", ""),
    "sort": ("What sort of music do you like?", "kind", ""),
    "rent": ("We rent a house near school.", "", ""),
    "commercial": ("The commercial lasted one minute.", "", ""),
    "ideal": ("This is an ideal place for a picnic.", "perfect", ""),
    "complex": ("The rule is too complex.", "complicated", "simple"),
    "junior": ("My junior asked for advice.", "", "senior"),
    "shut": ("Please shut the window.", "close", "open"),
    "bore": ("Long speeches bore me.", "", ""),
    "compose": ("He will compose a new song.", "", ""),
    "mend": ("Can you mend my broken chair?", "repair", ""),
    "inform": ("Please inform me of any change.", "tell", ""),
    "calculate": ("Calculate the total cost.", "", ""),
    "ordinary": ("It was an ordinary day.", "common", "special"),
    "selfish": ("Do not be selfish with your toys.", "", "generous"),
    "strict": ("My father is strict about bedtime.", "", ""),
    "sour": ("This lemon is very sour.", "", "sweet"),
    "solar": ("They installed solar panels.", "", "lunar"),
    "neither": ("Neither answer is correct.", "", ""),
    # ---------------- DAY 53
    "appetite": ("Exercise gives me a good appetite.", "", ""),
    "beast": ("A wild beast lives in this forest.", "", ""),
    "palm": ("She held the coin in her palm.", "", ""),
    "lab": ("We did the test in the lab.", "", ""),
    "horror": ("I never watch horror movies.", "", ""),
    "chore": ("Washing dishes is my daily chore.", "", ""),
    "outline": ("Write an outline before the essay.", "", ""),
    "crosswalk": ("Cross at the crosswalk only.", "", ""),
    "rhyme": ("These two words rhyme nicely.", "", ""),
    "charm": ("The village has an old charm.", "", ""),
    "force": ("Do not force him to eat.", "", ""),
    "function": ("This button has a special function.", "", ""),
    "contrast": ("The contrast between them is clear.", "difference", ""),
    "assist": ("A nurse will assist the doctor.", "help", ""),
    "employ": ("The farm will employ ten workers.", "hire", "fire"),
    "govern": ("A queen used to govern this land.", "rule", ""),
    "entertain": ("Clowns entertain the children.", "", ""),
    "criticize": ("Do not criticize your friends.", "", "praise"),
    "indicate": ("Dark clouds indicate rain.", "show", ""),
    "react": ("How did she react to the news?", "respond", ""),
    "dare": ("I dare not open the door.", "", ""),
    "obvious": ("The answer is obvious.", "clear", ""),
    "facial": ("His facial expression changed.", "", ""),
    "confident": ("She is confident about the test.", "sure", ""),
    "proper": ("Wear proper shoes for hiking.", "right", ""),
    "typical": ("This is a typical Korean meal.", "", ""),
    "outer": ("The outer wall needs paint.", "", "inner"),
    "realistic": ("Please set a realistic goal.", "", ""),
    "underwater": ("They took underwater photos.", "", ""),
    "fairly": ("The test was fairly easy.", "", ""),
    # ---------------- DAY 54
    "conductor": ("The conductor raised his baton.", "", ""),
    "court": ("The tennis court is wet.", "", ""),
    "dictation": ("We had a dictation test today.", "", ""),
    "jam": ("We were stuck in a traffic jam.", "", ""),
    "string": ("Tie the box with a string.", "", ""),
    "feather": ("A white feather fell slowly.", "", ""),
    "scale": ("The project has a large scale.", "", ""),
    "spot": ("This is a good spot for lunch.", "place", ""),
    "shame": ("What a shame you cannot come.", "", ""),
    "chemistry": ("Chemistry is my favorite science.", "", ""),
    "import": ("We import fruit from Chile.", "", "export"),
    "load": ("The truck carried a heavy load.", "", ""),
    "suspect": ("The police suspect the driver.", "doubt", ""),
    "pat": ("Give the dog a gentle pat.", "", ""),
    "liquid": ("Water is a clear liquid.", "", "solid"),
    "solid": ("Ice is water in solid form.", "", "liquid"),
    "leftover": ("We ate the leftover pizza.", "", ""),
    "evil": ("The evil king lost his throne.", "", "good"),
    "possess": ("They possess a large farm.", "own", ""),
    "contribute": ("Everyone can contribute a little.", "", ""),
    "recover": ("She will recover in a week.", "", ""),
    "ignore": ("Do not ignore the warning.", "", ""),
    "diligent": ("He is a diligent worker.", "", "lazy"),
    "pale": ("Your face looks pale.", "", ""),
    "brief": ("Give me a brief answer.", "short", ""),
    "rare": ("This bird is very rare.", "", "common"),
    "genetic": ("Eye color is a genetic trait.", "", ""),
    "organic": ("We buy organic vegetables.", "", ""),
    "holy": ("This is a holy place.", "sacred", ""),
    "unfortunately": ("Unfortunately, the shop was closed.", "", "fortunately"),
    # ---------------- DAY 55
    "anniversary": ("Today is their wedding anniversary.", "", ""),
    "nutrient": ("Milk contains an important nutrient.", "", ""),
    "grain": ("Rice is an important grain.", "", ""),
    "document": ("Please sign this document.", "", ""),
    "license": ("He got his driver's license.", "", ""),
    "department": ("She works in the sales department.", "", ""),
    "fortune": ("He made a fortune in business.", "", ""),
    "resource": ("Water is a precious resource.", "", ""),
    "hunger": ("Many children suffer from hunger.", "", ""),
    "error": ("There is an error in your answer.", "mistake", ""),
    "jail": ("The robber spent a year in jail.", "prison", ""),
    "request": ("I have a small request.", "", ""),
    "bomb": ("The old bomb was found safely.", "", ""),
    "poison": ("Some mushrooms contain poison.", "", ""),
    "wound": ("The wound healed in a week.", "injury", ""),
    "chase": ("Cats chase mice.", "", ""),
    "amaze": ("Her talent will amaze you.", "surprise", ""),
    "relieve": ("This medicine will relieve the pain.", "", ""),
    "motivate": ("Good teachers motivate students.", "encourage", ""),
    "afford": ("We cannot afford a new car.", "", ""),
    "absorb": ("Plants absorb water through roots.", "", ""),
    "attach": ("Attach the photo to the form.", "", ""),
    "cooperate": ("We must cooperate to finish this.", "", ""),
    "defend": ("Soldiers defend their country.", "protect", "attack"),
    "aware": ("Are you aware of the rule?", "", ""),
    "precious": ("Time is precious.", "valuable", ""),
    "political": ("He wrote a political article.", "", ""),
    "nuclear": ("Nuclear energy is powerful.", "", ""),
    "indoor": ("Table tennis is an indoor sport.", "", "outdoor"),
    "aloud": ("Please read the poem aloud.", "", ""),
    # ---------------- DAY 56
    "atmosphere": ("The atmosphere protects the earth.", "", ""),
    "voyage": ("The voyage took two months.", "journey", ""),
    "navy": ("His father served in the navy.", "", ""),
    "instrument": ("The violin is a beautiful instrument.", "", ""),
    "tube": ("Water flows through this tube.", "", ""),
    "leather": ("She bought a leather bag.", "", ""),
    "jewelry": ("Her jewelry box is full.", "", ""),
    "mud": ("The car was covered with mud.", "", ""),
    "target": ("The arrow hit the target.", "", ""),
    "aspect": ("Consider every aspect of the plan.", "side", ""),
    "anger": ("He could not hide his anger.", "", ""),
    "iron": ("The gate is made of iron.", "", ""),
    "comment": ("She made a short comment.", "remark", ""),
    "protest": ("Students protest against the rule.", "", ""),
    "concern": ("Safety is our main concern.", "", ""),
    "dump": ("Do not dump trash in the river.", "", ""),
    "enable": ("This app will enable fast payment.", "", ""),
    "annoy": ("Loud music can annoy neighbors.", "bother", ""),
    "insist": ("They insist on paying the bill.", "", ""),
    "combine": ("Combine the flour and sugar.", "mix", ""),
    "owe": ("I owe you five dollars.", "", ""),
    "suck": ("The baby likes to suck her thumb.", "", ""),
    "awake": ("I stayed awake until midnight.", "", "asleep"),
    "idle": ("Do not stay idle all day.", "lazy", ""),
    "previous": ("The previous owner painted it.", "former", "next"),
    "efficient": ("This method is very efficient.", "", ""),
    "rough": ("The road was rough and stony.", "", "smooth"),
    "severe": ("The storm caused severe damage.", "serious", ""),
    "romantic": ("They watched a romantic movie.", "", ""),
    "sometime": ("Let us meet sometime next week.", "", ""),
    # ---------------- DAY 57
    "democracy": ("Voting is the heart of democracy.", "", ""),
    "justice": ("The judge stands for justice.", "", ""),
    "faith": ("She has faith in her friends.", "trust", ""),
    "glory": ("The team returned in glory.", "", ""),
    "apology": ("He offered a sincere apology.", "", ""),
    "crisis": ("The country faced a food crisis.", "", ""),
    "debt": ("He paid back all his debt.", "", ""),
    "gap": ("There is a gap between the desks.", "", ""),
    "angle": ("Measure this angle carefully.", "", ""),
    "theory": ("His theory explains the result.", "", ""),
    "nest": ("Two eggs lay in the nest.", "", ""),
    "cycle": ("The water cycle never stops.", "", ""),
    "remark": ("His remark made us think.", "comment", ""),
    "comfort": ("Her words gave me comfort.", "", ""),
    "approach": ("Do not approach the wild dog.", "", ""),
    "struggle": ("They struggle against poverty.", "", ""),
    "content": ("Check the content of the box.", "", ""),
    "acid": ("Lemon juice contains acid.", "", ""),
    "differ": ("Our opinions differ a little.", "", ""),
    "deserve": ("You deserve a long rest.", "", ""),
    "permit": ("They do not permit dogs here.", "allow", "forbid"),
    "forbid": ("The rules forbid running inside.", "ban", "permit"),
    "reject": ("She may reject our offer.", "refuse", "accept"),
    "pure": ("This is pure spring water.", "clean", ""),
    "innocent": ("The court found him innocent.", "", "guilty"),
    "slight": ("There is a slight difference.", "small", ""),
    "particular": ("Is there a particular reason?", "specific", ""),
    "financial": ("They had financial trouble.", "", ""),
    "unexpected": ("His visit was unexpected.", "", ""),
    "aboard": ("All passengers are aboard.", "", ""),
    # ---------------- DAY 58
    "identity": ("The police checked his identity.", "", ""),
    "devil": ("The devil appears in the story.", "", "angel"),
    "spectator": ("Every spectator cheered loudly.", "", ""),
    "income": ("His monthly income is small.", "", ""),
    "tax": ("Everyone must pay tax.", "", ""),
    "fee": ("The entrance fee is two dollars.", "", ""),
    "fuel": ("The plane needs more fuel.", "", ""),
    "burden": ("The debt became a heavy burden.", "", ""),
    "variety": ("The shop sells a variety of hats.", "", ""),
    "sum": ("He paid a large sum of money.", "", ""),
    "profit": ("The store made a small profit.", "", "loss"),
    "process": ("Making cheese is a slow process.", "", ""),
    "exit": ("The exit is on your left.", "", "entrance"),
    "pop": ("The balloons pop very easily.", "", ""),
    "purchase": ("I will purchase two tickets.", "buy", ""),
    "defeat": ("Our team will defeat theirs.", "beat", "victory"),
    "persuade": ("She will persuade her parents.", "", ""),
    "cheat": ("Never cheat on a test.", "deceive", ""),
    "locate": ("Can you locate the town on the map?", "find", ""),
    "investigate": ("The police investigate the case.", "examine", ""),
    "distinguish": ("Can you distinguish the twins?", "", ""),
    "adopt": ("They will adopt a puppy.", "", ""),
    "usual": ("We met at the usual place.", "", "unusual"),
    "fashionable": ("That coat is very fashionable.", "", ""),
    "sufficient": ("We have sufficient food.", "enough", ""),
    "accurate": ("Her report is accurate.", "correct", ""),
    "complicated": ("The machine is complicated.", "complex", "simple"),
    "artificial": ("This flower is artificial.", "", "natural"),
    "tropical": ("Bananas grow in tropical areas.", "", ""),
    "hardly": ("I can hardly hear you.", "", ""),
    # ---------------- DAY 59
    "genius": ("Mozart was a musical genius.", "", ""),
    "servant": ("The servant opened the gate.", "", "master"),
    "profession": ("Teaching is a noble profession.", "", ""),
    "occupation": ("Please write your occupation here.", "job", ""),
    "surgery": ("He had surgery on his knee.", "operation", ""),
    "instruction": ("Follow the instruction on the box.", "", ""),
    "principle": ("She lives by a simple principle.", "", ""),
    "revolution": ("The revolution changed the country.", "", ""),
    "authority": ("The teacher has full authority here.", "power", ""),
    "rank": ("He rose to a high rank.", "", ""),
    "property": ("This land is private property.", "", ""),
    "advantage": ("Speed is our main advantage.", "benefit", "disadvantage"),
    "privacy": ("Everyone needs some privacy.", "", ""),
    "occasion": ("We met on a special occasion.", "", ""),
    "propose": ("I propose a short break.", "suggest", ""),
    "approve": ("My parents approve of my plan.", "", ""),
    "admit": ("He did admit his mistake.", "", "deny"),
    "conduct": ("They conduct a survey each year.", "", ""),
    "reserve": ("Please reserve a table for four.", "book", ""),
    "reveal": ("Do not reveal the secret.", "", "hide"),
    "donate": ("They donate books to the library.", "give", ""),
    "involve": ("The plan will involve everyone.", "include", ""),
    "definite": ("We need a definite answer.", "clear", ""),
    "urban": ("Urban life is busy.", "", "rural"),
    "addicted": ("He is addicted to games.", "", ""),
    "extreme": ("The desert has extreme heat.", "", ""),
    "academic": ("Her academic record is excellent.", "", ""),
    "guilty": ("He felt guilty about the lie.", "", "innocent"),
    "conscious": ("The patient is conscious now.", "awake", ""),
    "generally": ("Generally, winters here are mild.", "usually", ""),
    # ---------------- DAY 60
    "mankind": ("Fire changed the life of mankind.", "", ""),
    "poet": ("The poet read her own work.", "", ""),
    "detective": ("The detective solved the case.", "", ""),
    "consumer": ("Every consumer wants low prices.", "", ""),
    "chef": ("The chef cooked a fine meal.", "cook", ""),
    "passion": ("She has a passion for dance.", "", ""),
    "steel": ("The bridge is made of steel.", "", ""),
    "device": ("This device measures temperature.", "machine", ""),
    "pill": ("Take one pill after dinner.", "", ""),
    "ceiling": ("A lamp hangs from the ceiling.", "", "floor"),
    "aisle": ("Please keep the aisle clear.", "", ""),
    "appearance": ("Do not judge by appearance.", "look", ""),
    "destination": ("Our destination is Busan.", "", ""),
    "sweat": ("Sweat ran down his face.", "", ""),
    "switch": ("Turn the switch to the right.", "", ""),
    "grab": ("Do not grab my arm.", "", ""),
    "plain": ("The meaning is quite plain.", "clear", ""),
    "giant": ("A giant tree stood in the yard.", "", "tiny"),
    "found": ("They will found a new club.", "establish", ""),
    "seek": ("We seek a better answer.", "search", ""),
    "rob": ("Nobody will rob this bank.", "steal", ""),
    "swing": ("Children swing in the playground.", "", ""),
    "cancel": ("They had to cancel the concert.", "", ""),
    "avoid": ("Avoid the busy road at night.", "", ""),
    "rotten": ("Throw away the rotten apple.", "", "fresh"),
    "magnetic": ("This is a magnetic board.", "", ""),
    "steep": ("The hill is very steep.", "", ""),
    "logical": ("Her answer is logical.", "reasonable", ""),
    "ridiculous": ("That excuse sounds ridiculous.", "silly", ""),
    "upstairs": ("My room is upstairs.", "", "downstairs"),
}
